/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FormGUI;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;


/**
 *
 * @author Muhammad Dila
 */
public class FormLogin extends javax.swing.JFrame {

    Connection con =null;
    Statement st = null;
    
    public FormLogin() {
        initComponents();
        try {
                Class.forName("com.mysql.jdbc.Driver");
                con =DriverManager.getConnection("jdbc:mysql://localhost/db_tugasbesar_kelompok03","root","");
                st = con.createStatement();
            }
            catch(Exception ex){
            JOptionPane.showMessageDialog(null,"Gagal terkoneksiKarena " + ex);
            }
    }
    private void HapusTextField(){
    textEmail_Kelompok03.setText("");  
    textPassword_Kelompok03.setText("");
    }
    
    private void CekLogin(){
        try{
            if(textEmail_Kelompok03.getText().equals("") || textPassword_Kelompok03.getPassword().equals("")){
                JOptionPane.showMessageDialog(rootPane, "Data Tidak Boleh Kosong", "Pesan", JOptionPane.ERROR_MESSAGE);
                textEmail_Kelompok03.requestFocus();
                HapusTextField();
            }
            else{
                st = con.createStatement();
                String sql = ("SELECT * FROM t_akun_profile_pelanggan WHERE email ='" + textEmail_Kelompok03.getText()+"' AND password ='" + String.valueOf(textPassword_Kelompok03.getPassword())+"'");
                ResultSet rs = st.executeQuery(sql); 
                if(rs.next()){
                    JOptionPane.showMessageDialog(null, "Berhasil Masuk");
                    this.dispose();
                    new FormHome().setVisible(true);
                }
                else{
                    JOptionPane.showMessageDialog(rootPane, "UserName dan Password Salah\nAtau Akun Belum Terdaftar", "Pesan",
                    JOptionPane.ERROR_MESSAGE);
                }
            }
        }
        catch(Exception e){
            e.printStackTrace();
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_Kelompok03 = new javax.swing.JPanel();
        labelCartin_Kelompok03 = new javax.swing.JLabel();
        labelFood_Kelompok03 = new javax.swing.JLabel();
        labelSelamatDatang_Kelompok03 = new javax.swing.JLabel();
        labelMasukanAkun_Kelompok03 = new javax.swing.JLabel();
        labelBelumPunya_Kelompok03 = new javax.swing.JLabel();
        labelDaftar_Kelompok03 = new javax.swing.JLabel();
        panelEmail_Kelompok03 = new ClassForGUI.PanelRound();
        labelEmail_Kelompok03 = new javax.swing.JLabel();
        textEmail_Kelompok03 = new javax.swing.JTextField();
        labelIconEmail_Kelompok03 = new javax.swing.JLabel();
        panelPassword_Kelompok03 = new ClassForGUI.PanelRound();
        labelPassword_Kelompok03 = new javax.swing.JLabel();
        textPassword_Kelompok03 = new javax.swing.JPasswordField();
        labelIconPW_Kelompok03 = new javax.swing.JLabel();
        panelHapus_Kelompok03 = new ClassForGUI.PanelRound();
        labelHapus_Kelompok03 = new javax.swing.JLabel();
        panelMasukAkun_Kelompok03 = new ClassForGUI.PanelRound();
        labelMasukAkun_Kelompok03 = new javax.swing.JLabel();
        labelGambar_Kelompok03 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_Kelompok03.setBackground(new java.awt.Color(57, 161, 255));
        panel_Kelompok03.setPreferredSize(new java.awt.Dimension(1280, 720));
        panel_Kelompok03.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelCartin_Kelompok03.setFont(new java.awt.Font("Urbanist Black", 1, 24)); // NOI18N
        labelCartin_Kelompok03.setForeground(new java.awt.Color(255, 255, 255));
        labelCartin_Kelompok03.setText("CARTIN");
        panel_Kelompok03.add(labelCartin_Kelompok03, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 20, -1, -1));

        labelFood_Kelompok03.setFont(new java.awt.Font("Urbanist Black", 1, 24)); // NOI18N
        labelFood_Kelompok03.setForeground(new java.awt.Color(255, 176, 0));
        labelFood_Kelompok03.setText("FOOD");
        panel_Kelompok03.add(labelFood_Kelompok03, new org.netbeans.lib.awtextra.AbsoluteConstraints(845, 20, -1, -1));

        labelSelamatDatang_Kelompok03.setFont(new java.awt.Font("Urbanist", 1, 18)); // NOI18N
        labelSelamatDatang_Kelompok03.setForeground(new java.awt.Color(21, 0, 53));
        labelSelamatDatang_Kelompok03.setText("Selamat Datang");
        panel_Kelompok03.add(labelSelamatDatang_Kelompok03, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 200, -1, -1));

        labelMasukanAkun_Kelompok03.setFont(new java.awt.Font("Urbanist Black", 1, 36)); // NOI18N
        labelMasukanAkun_Kelompok03.setForeground(new java.awt.Color(21, 0, 53));
        labelMasukanAkun_Kelompok03.setText("Masukan Akun Anda.");
        panel_Kelompok03.add(labelMasukanAkun_Kelompok03, new org.netbeans.lib.awtextra.AbsoluteConstraints(748, 225, -1, -1));

        labelBelumPunya_Kelompok03.setFont(new java.awt.Font("Urbanist", 1, 18)); // NOI18N
        labelBelumPunya_Kelompok03.setForeground(new java.awt.Color(21, 0, 53));
        labelBelumPunya_Kelompok03.setText("Belum Punya Akun?");
        panel_Kelompok03.add(labelBelumPunya_Kelompok03, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 270, -1, -1));

        labelDaftar_Kelompok03.setFont(new java.awt.Font("Urbanist", 1, 18)); // NOI18N
        labelDaftar_Kelompok03.setForeground(new java.awt.Color(255, 176, 0));
        labelDaftar_Kelompok03.setText("Daftar");
        labelDaftar_Kelompok03.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelDaftar_Kelompok03.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                labelDaftar_Kelompok03MouseMoved(evt);
            }
        });
        labelDaftar_Kelompok03.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelDaftar_Kelompok03MouseClicked(evt);
            }
        });
        panel_Kelompok03.add(labelDaftar_Kelompok03, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 270, -1, -1));

        panelEmail_Kelompok03.setBackground(new java.awt.Color(255, 255, 255));
        panelEmail_Kelompok03.setRoundBottomLeft(25);
        panelEmail_Kelompok03.setRoundBottomRight(25);
        panelEmail_Kelompok03.setRoundTopLeft(25);
        panelEmail_Kelompok03.setRoundTopRight(25);
        panelEmail_Kelompok03.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelEmail_Kelompok03.setFont(new java.awt.Font("Urbanist", 1, 14)); // NOI18N
        labelEmail_Kelompok03.setForeground(new java.awt.Color(21, 0, 53));
        labelEmail_Kelompok03.setText("Email");
        panelEmail_Kelompok03.add(labelEmail_Kelompok03, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 5, -1, -1));

        textEmail_Kelompok03.setFont(new java.awt.Font("Urbanist", 1, 18)); // NOI18N
        textEmail_Kelompok03.setForeground(new java.awt.Color(21, 0, 53));
        textEmail_Kelompok03.setBorder(null);
        textEmail_Kelompok03.setOpaque(false);
        panelEmail_Kelompok03.add(textEmail_Kelompok03, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 30, 340, -1));

        labelIconEmail_Kelompok03.setFont(new java.awt.Font("Urbanist", 1, 14)); // NOI18N
        labelIconEmail_Kelompok03.setForeground(new java.awt.Color(21, 0, 53));
        labelIconEmail_Kelompok03.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelIconEmail_Kelompok03.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Icon Email.png"))); // NOI18N
        panelEmail_Kelompok03.add(labelIconEmail_Kelompok03, new org.netbeans.lib.awtextra.AbsoluteConstraints(375, 10, 40, 40));

        panel_Kelompok03.add(panelEmail_Kelompok03, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 320, 420, 60));

        panelPassword_Kelompok03.setBackground(new java.awt.Color(255, 255, 255));
        panelPassword_Kelompok03.setRoundBottomLeft(25);
        panelPassword_Kelompok03.setRoundBottomRight(25);
        panelPassword_Kelompok03.setRoundTopLeft(25);
        panelPassword_Kelompok03.setRoundTopRight(25);
        panelPassword_Kelompok03.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelPassword_Kelompok03.setFont(new java.awt.Font("Urbanist", 1, 14)); // NOI18N
        labelPassword_Kelompok03.setForeground(new java.awt.Color(21, 0, 53));
        labelPassword_Kelompok03.setText("Password");
        panelPassword_Kelompok03.add(labelPassword_Kelompok03, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 5, -1, -1));

        textPassword_Kelompok03.setFont(new java.awt.Font("Urbanist", 1, 18)); // NOI18N
        textPassword_Kelompok03.setForeground(new java.awt.Color(21, 0, 53));
        textPassword_Kelompok03.setBorder(null);
        textPassword_Kelompok03.setOpaque(false);
        panelPassword_Kelompok03.add(textPassword_Kelompok03, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 30, 350, -1));

        labelIconPW_Kelompok03.setFont(new java.awt.Font("Urbanist", 1, 14)); // NOI18N
        labelIconPW_Kelompok03.setForeground(new java.awt.Color(21, 0, 53));
        labelIconPW_Kelompok03.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelIconPW_Kelompok03.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Icon Password.png"))); // NOI18N
        panelPassword_Kelompok03.add(labelIconPW_Kelompok03, new org.netbeans.lib.awtextra.AbsoluteConstraints(375, 10, 40, 40));

        panel_Kelompok03.add(panelPassword_Kelompok03, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 400, 420, 60));

        panelHapus_Kelompok03.setBackground(new java.awt.Color(255, 255, 255));
        panelHapus_Kelompok03.setRoundBottomLeft(35);
        panelHapus_Kelompok03.setRoundBottomRight(35);
        panelHapus_Kelompok03.setRoundTopLeft(35);
        panelHapus_Kelompok03.setRoundTopRight(35);
        panelHapus_Kelompok03.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                panelHapus_Kelompok03MouseMoved(evt);
            }
        });
        panelHapus_Kelompok03.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelHapus_Kelompok03.setBackground(new java.awt.Color(102, 102, 102));
        labelHapus_Kelompok03.setFont(new java.awt.Font("Urbanist", 1, 18)); // NOI18N
        labelHapus_Kelompok03.setForeground(new java.awt.Color(21, 0, 53));
        labelHapus_Kelompok03.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelHapus_Kelompok03.setText("Hapus Field");
        labelHapus_Kelompok03.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelHapus_Kelompok03.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelHapus_Kelompok03MouseClicked(evt);
            }
        });
        panelHapus_Kelompok03.add(labelHapus_Kelompok03, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 15, 180, 30));

        panel_Kelompok03.add(panelHapus_Kelompok03, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 480, 200, 60));

        panelMasukAkun_Kelompok03.setBackground(new java.awt.Color(21, 0, 53));
        panelMasukAkun_Kelompok03.setRoundBottomLeft(35);
        panelMasukAkun_Kelompok03.setRoundBottomRight(35);
        panelMasukAkun_Kelompok03.setRoundTopLeft(35);
        panelMasukAkun_Kelompok03.setRoundTopRight(35);
        panelMasukAkun_Kelompok03.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                panelMasukAkun_Kelompok03MouseMoved(evt);
            }
        });
        panelMasukAkun_Kelompok03.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelMasukAkun_Kelompok03.setFont(new java.awt.Font("Urbanist", 1, 18)); // NOI18N
        labelMasukAkun_Kelompok03.setForeground(new java.awt.Color(255, 255, 255));
        labelMasukAkun_Kelompok03.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelMasukAkun_Kelompok03.setText("Masuk");
        labelMasukAkun_Kelompok03.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelMasukAkun_Kelompok03.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                labelMasukAkun_Kelompok03MouseMoved(evt);
            }
        });
        labelMasukAkun_Kelompok03.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelMasukAkun_Kelompok03MouseClicked(evt);
            }
        });
        panelMasukAkun_Kelompok03.add(labelMasukAkun_Kelompok03, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 15, 180, 30));

        panel_Kelompok03.add(panelMasukAkun_Kelompok03, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 480, 200, 60));

        labelGambar_Kelompok03.setFont(new java.awt.Font("Urbanist", 1, 18)); // NOI18N
        labelGambar_Kelompok03.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Form Login.png"))); // NOI18N
        labelGambar_Kelompok03.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                labelGambar_Kelompok03MouseMoved(evt);
            }
        });
        panel_Kelompok03.add(labelGambar_Kelompok03, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 5, 1280, 720));

        getContentPane().add(panel_Kelompok03, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        setSize(new java.awt.Dimension(1296, 759));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void labelDaftar_Kelompok03MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelDaftar_Kelompok03MouseMoved
        // TODO add your handling code here:
        labelDaftar_Kelompok03.setForeground(new java.awt.Color(255, 225, 225));
    }//GEN-LAST:event_labelDaftar_Kelompok03MouseMoved

    private void labelGambar_Kelompok03MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelGambar_Kelompok03MouseMoved
        // TODO add your handling code here:
        labelDaftar_Kelompok03.setForeground(new java.awt.Color(255, 176, 0));
        panelHapus_Kelompok03.setBackground(new java.awt.Color(255, 255, 255));
        panelMasukAkun_Kelompok03.setBackground(new java.awt.Color(21, 0, 53));
        labelMasukAkun_Kelompok03.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_labelGambar_Kelompok03MouseMoved

    private void panelHapus_Kelompok03MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelHapus_Kelompok03MouseMoved
        // TODO add your handling code here:
        panelHapus_Kelompok03.setBackground(new java.awt.Color(255, 176, 0));
    }//GEN-LAST:event_panelHapus_Kelompok03MouseMoved

    private void panelMasukAkun_Kelompok03MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelMasukAkun_Kelompok03MouseMoved
        // TODO add your handling code here:
        panelMasukAkun_Kelompok03.setBackground(new java.awt.Color(255, 176, 0));
        labelMasukAkun_Kelompok03.setForeground(new java.awt.Color(21, 0, 53));
    }//GEN-LAST:event_panelMasukAkun_Kelompok03MouseMoved

    private void labelMasukAkun_Kelompok03MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelMasukAkun_Kelompok03MouseMoved
        // TODO add your handling code here:
        labelMasukAkun_Kelompok03.setForeground(new java.awt.Color(21, 0, 53));
        panelMasukAkun_Kelompok03.setBackground(new java.awt.Color(255, 176, 0));
    }//GEN-LAST:event_labelMasukAkun_Kelompok03MouseMoved

    private void labelHapus_Kelompok03MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelHapus_Kelompok03MouseClicked
        // TODO add your handling code here:
        HapusTextField();
    }//GEN-LAST:event_labelHapus_Kelompok03MouseClicked

    private void labelDaftar_Kelompok03MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelDaftar_Kelompok03MouseClicked
        // TODO add your handling code here:
        FormDaftar s = new FormDaftar();
        s.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_labelDaftar_Kelompok03MouseClicked

    private void labelMasukAkun_Kelompok03MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelMasukAkun_Kelompok03MouseClicked
        // TODO add your handling code here:
        CekLogin();
    }//GEN-LAST:event_labelMasukAkun_Kelompok03MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel labelBelumPunya_Kelompok03;
    private javax.swing.JLabel labelCartin_Kelompok03;
    private javax.swing.JLabel labelDaftar_Kelompok03;
    private javax.swing.JLabel labelEmail_Kelompok03;
    private javax.swing.JLabel labelFood_Kelompok03;
    private javax.swing.JLabel labelGambar_Kelompok03;
    private javax.swing.JLabel labelHapus_Kelompok03;
    private javax.swing.JLabel labelIconEmail_Kelompok03;
    private javax.swing.JLabel labelIconPW_Kelompok03;
    private javax.swing.JLabel labelMasukAkun_Kelompok03;
    private javax.swing.JLabel labelMasukanAkun_Kelompok03;
    private javax.swing.JLabel labelPassword_Kelompok03;
    private javax.swing.JLabel labelSelamatDatang_Kelompok03;
    private ClassForGUI.PanelRound panelEmail_Kelompok03;
    private ClassForGUI.PanelRound panelHapus_Kelompok03;
    private ClassForGUI.PanelRound panelMasukAkun_Kelompok03;
    private ClassForGUI.PanelRound panelPassword_Kelompok03;
    private javax.swing.JPanel panel_Kelompok03;
    public static javax.swing.JTextField textEmail_Kelompok03;
    private javax.swing.JPasswordField textPassword_Kelompok03;
    // End of variables declaration//GEN-END:variables
}
