/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FormGUI;

import Database.Database;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Muhammad Dila
 */
public class FormDaftar extends javax.swing.JFrame {

    Connection con =null;
    Statement st = null;
    
    public FormDaftar() {
        initComponents();
        kodePelangganOtomatis();
        TampilkanData();
    }
    
    private void HapusTextField(){
    textNamaDepan_Kelompok03.setText("");
    textNamaBelakang_Kelompok03.setText("");
    textEmail_Kelompok03.setText("");
    textPassword_Kelompok03.setText("");   
    }
    
    public Connection setKoneksi(){
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con=DriverManager.getConnection("jdbc:mysql://localhost/db_tugasbesar_kelompok03","root","");
            st=con.createStatement();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Koneksi Gagal :" +e);
        }
       return con; 
    }
    
    private void kodePelangganOtomatis(){
        try {
            setKoneksi();
            String sql="select right (kode_pelanggan,2)+1 from t_akun_profile_pelanggan";
            ResultSet rs=st.executeQuery(sql);
              
            if(rs.next()){
                rs.last();
                String no=rs.getString(1);
                while (no.length()<3){
                    no="0"+no;
                    textKodePelanggan_Kelompok03.setText("KP"+no);}
                }
            else 
            {
                textKodePelanggan_Kelompok03.setText("KP001"); 
            }
            } catch (Exception e) 
            {
        }
    }
    
    private void TampilkanData(){
        
        DefaultTableModel model= new DefaultTableModel();
        model.addColumn("K. Pelanggan");
        model.addColumn("email");
        try{
            String sql="SELECT * FROM t_akun_profile_pelanggan";
            java.sql.Connection conn = (Connection)Database.configDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);
            
            while(res.next()){
                model.addRow(new Object[]{res.getString(1),res.getString(12)});
                
            }
            jTable1.setModel(model);
        }catch (SQLException e){
            System.out.println("Error : " + e.getMessage());
        }
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_Kelompok03 = new javax.swing.JPanel();
        labelCartin_Kelompok03 = new javax.swing.JLabel();
        labelFood_Kelompok03 = new javax.swing.JLabel();
        labelMulaiGratis_Kelompok03 = new javax.swing.JLabel();
        labelDaftarAkun_Kelompok03 = new javax.swing.JLabel();
        labelSudahPunya_Kelompok03 = new javax.swing.JLabel();
        labelMasuk_Kelompok03 = new javax.swing.JLabel();
        panelNamaDepan_Kelompok03 = new ClassForGUI.PanelRound();
        labelIconNamaDepan_Kelompok03 = new javax.swing.JLabel();
        labelNamaDepan_Kelompok5 = new javax.swing.JLabel();
        textNamaDepan_Kelompok03 = new javax.swing.JTextField();
        panelNamaBelakang_Kelompok03 = new ClassForGUI.PanelRound();
        labelIconNamaBelakang_Kelompok03 = new javax.swing.JLabel();
        labelNamaBelakang_Kelompok03 = new javax.swing.JLabel();
        textNamaBelakang_Kelompok03 = new javax.swing.JTextField();
        panelEmail_Kelompok03 = new ClassForGUI.PanelRound();
        labelIconEmail_Kelompok03 = new javax.swing.JLabel();
        labelEmail_Kelompok03 = new javax.swing.JLabel();
        textEmail_Kelompok03 = new javax.swing.JTextField();
        panelPassword_Kelompok03 = new ClassForGUI.PanelRound();
        labelPassword_Kelompok03 = new javax.swing.JLabel();
        textPassword_Kelompok03 = new javax.swing.JPasswordField();
        labelIconPW_Kelompok03 = new javax.swing.JLabel();
        panelHapus_Kelompok03 = new ClassForGUI.PanelRound();
        labelHapus_Kelompok03 = new javax.swing.JLabel();
        panelBuatAkun_Kelompok03 = new ClassForGUI.PanelRound();
        labelBuatAkun_Kelompok03 = new javax.swing.JLabel();
        panelRahasia_Kelompok03 = new ClassForGUI.PanelRound();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        textKodePelanggan_Kelompok03 = new javax.swing.JTextField();
        labelGambar_Kelompok03 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_Kelompok03.setBackground(new java.awt.Color(57, 161, 255));
        panel_Kelompok03.setPreferredSize(new java.awt.Dimension(1280, 720));
        panel_Kelompok03.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelCartin_Kelompok03.setFont(new java.awt.Font("Urbanist Black", 1, 24)); // NOI18N
        labelCartin_Kelompok03.setForeground(new java.awt.Color(255, 255, 255));
        labelCartin_Kelompok03.setText("CARTIN");
        panel_Kelompok03.add(labelCartin_Kelompok03, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, -1, -1));

        labelFood_Kelompok03.setFont(new java.awt.Font("Urbanist Black", 1, 24)); // NOI18N
        labelFood_Kelompok03.setForeground(new java.awt.Color(255, 176, 0));
        labelFood_Kelompok03.setText("FOOD");
        panel_Kelompok03.add(labelFood_Kelompok03, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 20, -1, -1));

        labelMulaiGratis_Kelompok03.setFont(new java.awt.Font("Urbanist", 1, 18)); // NOI18N
        labelMulaiGratis_Kelompok03.setForeground(new java.awt.Color(21, 0, 53));
        labelMulaiGratis_Kelompok03.setText("Mulai Gratis");
        panel_Kelompok03.add(labelMulaiGratis_Kelompok03, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, -1, -1));

        labelDaftarAkun_Kelompok03.setFont(new java.awt.Font("Urbanist Black", 1, 36)); // NOI18N
        labelDaftarAkun_Kelompok03.setForeground(new java.awt.Color(21, 0, 53));
        labelDaftarAkun_Kelompok03.setText("Daftar Akun Baru.");
        panel_Kelompok03.add(labelDaftarAkun_Kelompok03, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 175, -1, -1));

        labelSudahPunya_Kelompok03.setFont(new java.awt.Font("Urbanist", 1, 18)); // NOI18N
        labelSudahPunya_Kelompok03.setForeground(new java.awt.Color(21, 0, 53));
        labelSudahPunya_Kelompok03.setText("Sudah Punya Akun?");
        panel_Kelompok03.add(labelSudahPunya_Kelompok03, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, -1, -1));

        labelMasuk_Kelompok03.setFont(new java.awt.Font("Urbanist", 1, 18)); // NOI18N
        labelMasuk_Kelompok03.setForeground(new java.awt.Color(255, 176, 0));
        labelMasuk_Kelompok03.setText("Masuk");
        labelMasuk_Kelompok03.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelMasuk_Kelompok03.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                labelMasuk_Kelompok03MouseMoved(evt);
            }
        });
        labelMasuk_Kelompok03.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelMasuk_Kelompok03MouseClicked(evt);
            }
        });
        panel_Kelompok03.add(labelMasuk_Kelompok03, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 220, -1, -1));

        panelNamaDepan_Kelompok03.setBackground(new java.awt.Color(255, 255, 255));
        panelNamaDepan_Kelompok03.setRoundBottomLeft(25);
        panelNamaDepan_Kelompok03.setRoundBottomRight(25);
        panelNamaDepan_Kelompok03.setRoundTopLeft(25);
        panelNamaDepan_Kelompok03.setRoundTopRight(25);
        panelNamaDepan_Kelompok03.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelIconNamaDepan_Kelompok03.setFont(new java.awt.Font("Urbanist", 1, 14)); // NOI18N
        labelIconNamaDepan_Kelompok03.setForeground(new java.awt.Color(21, 0, 53));
        labelIconNamaDepan_Kelompok03.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelIconNamaDepan_Kelompok03.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Icon Nama.png"))); // NOI18N
        panelNamaDepan_Kelompok03.add(labelIconNamaDepan_Kelompok03, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 10, 40, 40));

        labelNamaDepan_Kelompok5.setFont(new java.awt.Font("Urbanist", 1, 14)); // NOI18N
        labelNamaDepan_Kelompok5.setForeground(new java.awt.Color(21, 0, 53));
        labelNamaDepan_Kelompok5.setText("Nama Depan");
        panelNamaDepan_Kelompok03.add(labelNamaDepan_Kelompok5, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 5, -1, -1));

        textNamaDepan_Kelompok03.setFont(new java.awt.Font("Urbanist", 1, 18)); // NOI18N
        textNamaDepan_Kelompok03.setForeground(new java.awt.Color(21, 0, 53));
        textNamaDepan_Kelompok03.setBorder(null);
        textNamaDepan_Kelompok03.setOpaque(false);
        panelNamaDepan_Kelompok03.add(textNamaDepan_Kelompok03, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 30, 150, 20));

        panel_Kelompok03.add(panelNamaDepan_Kelompok03, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, 200, 60));

        panelNamaBelakang_Kelompok03.setBackground(new java.awt.Color(255, 255, 255));
        panelNamaBelakang_Kelompok03.setRoundBottomLeft(25);
        panelNamaBelakang_Kelompok03.setRoundBottomRight(25);
        panelNamaBelakang_Kelompok03.setRoundTopLeft(25);
        panelNamaBelakang_Kelompok03.setRoundTopRight(25);
        panelNamaBelakang_Kelompok03.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelIconNamaBelakang_Kelompok03.setFont(new java.awt.Font("Urbanist", 1, 14)); // NOI18N
        labelIconNamaBelakang_Kelompok03.setForeground(new java.awt.Color(21, 0, 53));
        labelIconNamaBelakang_Kelompok03.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelIconNamaBelakang_Kelompok03.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Icon Nama.png"))); // NOI18N
        panelNamaBelakang_Kelompok03.add(labelIconNamaBelakang_Kelompok03, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 10, 40, 40));

        labelNamaBelakang_Kelompok03.setFont(new java.awt.Font("Urbanist", 1, 14)); // NOI18N
        labelNamaBelakang_Kelompok03.setForeground(new java.awt.Color(21, 0, 53));
        labelNamaBelakang_Kelompok03.setText("Nama Belakang");
        panelNamaBelakang_Kelompok03.add(labelNamaBelakang_Kelompok03, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 5, -1, -1));

        textNamaBelakang_Kelompok03.setFont(new java.awt.Font("Urbanist", 1, 18)); // NOI18N
        textNamaBelakang_Kelompok03.setForeground(new java.awt.Color(21, 0, 53));
        textNamaBelakang_Kelompok03.setBorder(null);
        textNamaBelakang_Kelompok03.setOpaque(false);
        panelNamaBelakang_Kelompok03.add(textNamaBelakang_Kelompok03, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 30, 150, -1));

        panel_Kelompok03.add(panelNamaBelakang_Kelompok03, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 270, 200, 60));

        panelEmail_Kelompok03.setBackground(new java.awt.Color(255, 255, 255));
        panelEmail_Kelompok03.setRoundBottomLeft(25);
        panelEmail_Kelompok03.setRoundBottomRight(25);
        panelEmail_Kelompok03.setRoundTopLeft(25);
        panelEmail_Kelompok03.setRoundTopRight(25);
        panelEmail_Kelompok03.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelIconEmail_Kelompok03.setFont(new java.awt.Font("Urbanist", 1, 14)); // NOI18N
        labelIconEmail_Kelompok03.setForeground(new java.awt.Color(21, 0, 53));
        labelIconEmail_Kelompok03.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelIconEmail_Kelompok03.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Icon Email.png"))); // NOI18N
        panelEmail_Kelompok03.add(labelIconEmail_Kelompok03, new org.netbeans.lib.awtextra.AbsoluteConstraints(375, 10, 40, 40));

        labelEmail_Kelompok03.setFont(new java.awt.Font("Urbanist", 1, 14)); // NOI18N
        labelEmail_Kelompok03.setForeground(new java.awt.Color(21, 0, 53));
        labelEmail_Kelompok03.setText("Email");
        panelEmail_Kelompok03.add(labelEmail_Kelompok03, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 5, -1, -1));

        textEmail_Kelompok03.setFont(new java.awt.Font("Urbanist", 1, 18)); // NOI18N
        textEmail_Kelompok03.setForeground(new java.awt.Color(21, 0, 53));
        textEmail_Kelompok03.setBorder(null);
        textEmail_Kelompok03.setOpaque(false);
        panelEmail_Kelompok03.add(textEmail_Kelompok03, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 30, 340, -1));

        panel_Kelompok03.add(panelEmail_Kelompok03, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 350, 420, 60));

        panelPassword_Kelompok03.setBackground(new java.awt.Color(255, 255, 255));
        panelPassword_Kelompok03.setRoundBottomLeft(25);
        panelPassword_Kelompok03.setRoundBottomRight(25);
        panelPassword_Kelompok03.setRoundTopLeft(25);
        panelPassword_Kelompok03.setRoundTopRight(25);
        panelPassword_Kelompok03.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelPassword_Kelompok03.setFont(new java.awt.Font("Urbanist", 1, 14)); // NOI18N
        labelPassword_Kelompok03.setForeground(new java.awt.Color(21, 0, 53));
        labelPassword_Kelompok03.setText("Password");
        panelPassword_Kelompok03.add(labelPassword_Kelompok03, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 5, -1, -1));

        textPassword_Kelompok03.setFont(new java.awt.Font("Urbanist", 1, 18)); // NOI18N
        textPassword_Kelompok03.setForeground(new java.awt.Color(21, 0, 53));
        textPassword_Kelompok03.setBorder(null);
        textPassword_Kelompok03.setOpaque(false);
        panelPassword_Kelompok03.add(textPassword_Kelompok03, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 30, 350, -1));

        labelIconPW_Kelompok03.setFont(new java.awt.Font("Urbanist", 1, 14)); // NOI18N
        labelIconPW_Kelompok03.setForeground(new java.awt.Color(21, 0, 53));
        labelIconPW_Kelompok03.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelIconPW_Kelompok03.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Icon Password.png"))); // NOI18N
        panelPassword_Kelompok03.add(labelIconPW_Kelompok03, new org.netbeans.lib.awtextra.AbsoluteConstraints(375, 10, 40, 40));

        panel_Kelompok03.add(panelPassword_Kelompok03, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 430, 420, 60));

        panelHapus_Kelompok03.setBackground(new java.awt.Color(255, 255, 255));
        panelHapus_Kelompok03.setRoundBottomLeft(35);
        panelHapus_Kelompok03.setRoundBottomRight(35);
        panelHapus_Kelompok03.setRoundTopLeft(35);
        panelHapus_Kelompok03.setRoundTopRight(35);
        panelHapus_Kelompok03.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                panelHapus_Kelompok03MouseMoved(evt);
            }
        });
        panelHapus_Kelompok03.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelHapus_Kelompok03.setBackground(new java.awt.Color(102, 102, 102));
        labelHapus_Kelompok03.setFont(new java.awt.Font("Urbanist", 1, 18)); // NOI18N
        labelHapus_Kelompok03.setForeground(new java.awt.Color(21, 0, 53));
        labelHapus_Kelompok03.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelHapus_Kelompok03.setText("Hapus Field");
        labelHapus_Kelompok03.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelHapus_Kelompok03.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelHapus_Kelompok03MouseClicked(evt);
            }
        });
        panelHapus_Kelompok03.add(labelHapus_Kelompok03, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 15, 180, 30));

        panel_Kelompok03.add(panelHapus_Kelompok03, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 510, 200, 60));

        panelBuatAkun_Kelompok03.setBackground(new java.awt.Color(21, 0, 53));
        panelBuatAkun_Kelompok03.setRoundBottomLeft(35);
        panelBuatAkun_Kelompok03.setRoundBottomRight(35);
        panelBuatAkun_Kelompok03.setRoundTopLeft(35);
        panelBuatAkun_Kelompok03.setRoundTopRight(35);
        panelBuatAkun_Kelompok03.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                panelBuatAkun_Kelompok03MouseMoved(evt);
            }
        });
        panelBuatAkun_Kelompok03.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelBuatAkun_Kelompok03.setFont(new java.awt.Font("Urbanist", 1, 18)); // NOI18N
        labelBuatAkun_Kelompok03.setForeground(new java.awt.Color(255, 255, 255));
        labelBuatAkun_Kelompok03.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelBuatAkun_Kelompok03.setText("Buat Akun Baru");
        labelBuatAkun_Kelompok03.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelBuatAkun_Kelompok03.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                labelBuatAkun_Kelompok03MouseMoved(evt);
            }
        });
        labelBuatAkun_Kelompok03.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelBuatAkun_Kelompok03MouseClicked(evt);
            }
        });
        panelBuatAkun_Kelompok03.add(labelBuatAkun_Kelompok03, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 15, 180, 30));

        panel_Kelompok03.add(panelBuatAkun_Kelompok03, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 510, 200, 60));

        panelRahasia_Kelompok03.setBackground(new java.awt.Color(255, 255, 255));
        panelRahasia_Kelompok03.setRoundBottomLeft(25);
        panelRahasia_Kelompok03.setRoundBottomRight(25);
        panelRahasia_Kelompok03.setRoundTopLeft(25);
        panelRahasia_Kelompok03.setRoundTopRight(25);
        panelRahasia_Kelompok03.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        panelRahasia_Kelompok03.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 270, 150));

        textKodePelanggan_Kelompok03.setFont(new java.awt.Font("Urbanist", 1, 18)); // NOI18N
        textKodePelanggan_Kelompok03.setForeground(new java.awt.Color(21, 0, 53));
        textKodePelanggan_Kelompok03.setBorder(null);
        textKodePelanggan_Kelompok03.setEnabled(false);
        textKodePelanggan_Kelompok03.setOpaque(false);
        textKodePelanggan_Kelompok03.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textKodePelanggan_Kelompok03ActionPerformed(evt);
            }
        });
        panelRahasia_Kelompok03.add(textKodePelanggan_Kelompok03, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 150, 20));

        panel_Kelompok03.add(panelRahasia_Kelompok03, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 50, 300, 0));

        labelGambar_Kelompok03.setFont(new java.awt.Font("Urbanist", 1, 18)); // NOI18N
        labelGambar_Kelompok03.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Form Daftar.png"))); // NOI18N
        labelGambar_Kelompok03.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                labelGambar_Kelompok03MouseMoved(evt);
            }
        });
        panel_Kelompok03.add(labelGambar_Kelompok03, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 5, 1280, 720));

        getContentPane().add(panel_Kelompok03, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        setSize(new java.awt.Dimension(1296, 759));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void labelMasuk_Kelompok03MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelMasuk_Kelompok03MouseMoved
        // TODO add your handling code here:
        labelMasuk_Kelompok03.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_labelMasuk_Kelompok03MouseMoved

    private void labelGambar_Kelompok03MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelGambar_Kelompok03MouseMoved
        // TODO add your handling code here:
        labelMasuk_Kelompok03.setForeground(new java.awt.Color(255, 176, 0));
        panelHapus_Kelompok03.setBackground(new java.awt.Color(255, 255, 255));
        panelBuatAkun_Kelompok03.setBackground(new java.awt.Color(21, 0, 53));
        labelBuatAkun_Kelompok03.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_labelGambar_Kelompok03MouseMoved

    private void panelHapus_Kelompok03MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelHapus_Kelompok03MouseMoved
        // TODO add your handling code here:
        panelHapus_Kelompok03.setBackground(new java.awt.Color(255, 176, 0));
    }//GEN-LAST:event_panelHapus_Kelompok03MouseMoved

    private void labelBuatAkun_Kelompok03MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelBuatAkun_Kelompok03MouseMoved
        // TODO add your handling code here:
        panelBuatAkun_Kelompok03.setBackground(new java.awt.Color(255, 176, 0));
        labelBuatAkun_Kelompok03.setForeground(new java.awt.Color(21, 0, 53));
    }//GEN-LAST:event_labelBuatAkun_Kelompok03MouseMoved

    private void panelBuatAkun_Kelompok03MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelBuatAkun_Kelompok03MouseMoved
        // TODO add your handling code here:
        panelBuatAkun_Kelompok03.setBackground(new java.awt.Color(255, 176, 0));
        labelBuatAkun_Kelompok03.setForeground(new java.awt.Color(21, 0, 53));
    }//GEN-LAST:event_panelBuatAkun_Kelompok03MouseMoved

    private void labelHapus_Kelompok03MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelHapus_Kelompok03MouseClicked
        // TODO add your handling code here:
        panelHapus_Kelompok03.setBackground(new java.awt.Color(255, 176, 0));
        HapusTextField();
    }//GEN-LAST:event_labelHapus_Kelompok03MouseClicked

    private void labelMasuk_Kelompok03MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelMasuk_Kelompok03MouseClicked
        // TODO add your handling code here:
        FormLogin s = new FormLogin();
        s.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_labelMasuk_Kelompok03MouseClicked

    private void labelBuatAkun_Kelompok03MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelBuatAkun_Kelompok03MouseClicked
        // TODO add your handling code here:
        String defaultKata = " ";
        try {
            if (textNamaBelakang_Kelompok03.getText().equals("") || textNamaDepan_Kelompok03.getText().equals("") 
                   || textEmail_Kelompok03.getText().equals("") || textPassword_Kelompok03.getPassword().equals("")) {
                JOptionPane.showMessageDialog(this, "Data Tidak Boleh Kosong", "Pesan", JOptionPane.ERROR_MESSAGE);
            }
            else {
                Class.forName("com.mysql.jdbc.Driver");
                con = DriverManager.getConnection("jdbc:mysql://localhost/db_tugasbesar_kelompok03", "root" ,"");
                st=con.createStatement();
                
                String simpan = "INSERT INTO t_akun_profile_pelanggan VALUES ('"+ textKodePelanggan_Kelompok03.getText() + "','" + textNamaDepan_Kelompok03.getText() +  "','" + defaultKata 
                        + textNamaBelakang_Kelompok03.getText() + "','" + defaultKata + "','" + defaultKata + "','" + defaultKata + "','" 
                        + defaultKata + "','" + defaultKata + "','" + defaultKata + "','" + defaultKata + "','" + defaultKata + "','" + textEmail_Kelompok03.getText() + "','"
                        + String.valueOf(textPassword_Kelompok03.getPassword())+ "')";
                
                int SA = st.executeUpdate(simpan);
                JOptionPane.showMessageDialog(null, "Daftar Akun Berhasil");
                kodePelangganOtomatis();
                this.setVisible(false);
                new FormLogin().setVisible(true);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Akun Sudah Terdaftar \nSilahkan Coba Lagi", "Pesan",
            JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_labelBuatAkun_Kelompok03MouseClicked

    private void textKodePelanggan_Kelompok03ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textKodePelanggan_Kelompok03ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textKodePelanggan_Kelompok03ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int baris=jTable1.rowAtPoint(evt.getPoint());
        String kodeBarang = jTable1.getValueAt(baris,0).toString();
        textKodePelanggan_Kelompok03.setText(kodeBarang);
        kodePelangganOtomatis();
    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormDaftar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormDaftar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormDaftar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormDaftar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormDaftar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel labelBuatAkun_Kelompok03;
    private javax.swing.JLabel labelCartin_Kelompok03;
    private javax.swing.JLabel labelDaftarAkun_Kelompok03;
    private javax.swing.JLabel labelEmail_Kelompok03;
    private javax.swing.JLabel labelFood_Kelompok03;
    private javax.swing.JLabel labelGambar_Kelompok03;
    private javax.swing.JLabel labelHapus_Kelompok03;
    private javax.swing.JLabel labelIconEmail_Kelompok03;
    private javax.swing.JLabel labelIconNamaBelakang_Kelompok03;
    private javax.swing.JLabel labelIconNamaDepan_Kelompok03;
    private javax.swing.JLabel labelIconPW_Kelompok03;
    private javax.swing.JLabel labelMasuk_Kelompok03;
    private javax.swing.JLabel labelMulaiGratis_Kelompok03;
    private javax.swing.JLabel labelNamaBelakang_Kelompok03;
    private javax.swing.JLabel labelNamaDepan_Kelompok5;
    private javax.swing.JLabel labelPassword_Kelompok03;
    private javax.swing.JLabel labelSudahPunya_Kelompok03;
    private ClassForGUI.PanelRound panelBuatAkun_Kelompok03;
    private ClassForGUI.PanelRound panelEmail_Kelompok03;
    private ClassForGUI.PanelRound panelHapus_Kelompok03;
    private ClassForGUI.PanelRound panelNamaBelakang_Kelompok03;
    private ClassForGUI.PanelRound panelNamaDepan_Kelompok03;
    private ClassForGUI.PanelRound panelPassword_Kelompok03;
    private ClassForGUI.PanelRound panelRahasia_Kelompok03;
    private javax.swing.JPanel panel_Kelompok03;
    private javax.swing.JTextField textEmail_Kelompok03;
    private javax.swing.JTextField textKodePelanggan_Kelompok03;
    private javax.swing.JTextField textNamaBelakang_Kelompok03;
    private javax.swing.JTextField textNamaDepan_Kelompok03;
    private javax.swing.JPasswordField textPassword_Kelompok03;
    // End of variables declaration//GEN-END:variables
}
