/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FormGUI;

/**
 *
 * @author Muhammad Dila
 */
public class FormHomeAdmin extends javax.swing.JFrame {

    /**
     * Creates new form FormLogin
     */
    public FormHomeAdmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_Kelompok03 = new javax.swing.JPanel();
        labelCartin_Kelompok03 = new javax.swing.JLabel();
        labelFood_Kelompok03 = new javax.swing.JLabel();
        labelHome_Kelompok03 = new javax.swing.JLabel();
        labelBahanBaku_Kelompok03 = new javax.swing.JLabel();
        labelBarang_Kelompok03 = new javax.swing.JLabel();
        labelPelanggan_Kelompok03 = new javax.swing.JLabel();
        labelKeluar_Kelompok03 = new javax.swing.JLabel();
        labelTransaksi_Kelompok03 = new javax.swing.JLabel();
        panelGaris_Kelompok03 = new ClassForGUI.PanelRound();
        labelSilahkanPesan_Kelompok03 = new javax.swing.JLabel();
        labelKet1_Kelompok03 = new javax.swing.JLabel();
        labelKet2_Kelompok03 = new javax.swing.JLabel();
        labelKet3_Kelompok03 = new javax.swing.JLabel();
        panelDataBarang_Kelompok03 = new ClassForGUI.PanelRound();
        labelDataBarang_Kelompok03 = new javax.swing.JLabel();
        panelDataPelanggan_Kelompok03 = new ClassForGUI.PanelRound();
        labelDataPelanggan_Kelompok03 = new javax.swing.JLabel();
        panelDataBahanBaku_Kelompok03 = new ClassForGUI.PanelRound();
        labelDataBahanBaku_Kelompok03 = new javax.swing.JLabel();
        panelDataTransaksi_Kelompok03 = new ClassForGUI.PanelRound();
        labelDataTransaksi_Kelompok03 = new javax.swing.JLabel();
        labelGambar_Kelompok03 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_Kelompok03.setBackground(new java.awt.Color(255, 176, 0));
        panel_Kelompok03.setPreferredSize(new java.awt.Dimension(1280, 720));
        panel_Kelompok03.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelCartin_Kelompok03.setFont(new java.awt.Font("Urbanist Black", 1, 24)); // NOI18N
        labelCartin_Kelompok03.setForeground(new java.awt.Color(255, 255, 255));
        labelCartin_Kelompok03.setText("CARTIN");
        labelCartin_Kelompok03.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panel_Kelompok03.add(labelCartin_Kelompok03, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 25, 170, -1));

        labelFood_Kelompok03.setFont(new java.awt.Font("Urbanist Black", 1, 24)); // NOI18N
        labelFood_Kelompok03.setForeground(new java.awt.Color(57, 161, 255));
        labelFood_Kelompok03.setText("FOOD");
        panel_Kelompok03.add(labelFood_Kelompok03, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 25, -1, -1));

        labelHome_Kelompok03.setFont(new java.awt.Font("Urbanist", 1, 20)); // NOI18N
        labelHome_Kelompok03.setForeground(new java.awt.Color(21, 0, 53));
        labelHome_Kelompok03.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Icon Home.png"))); // NOI18N
        labelHome_Kelompok03.setText("Home");
        labelHome_Kelompok03.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelHome_Kelompok03.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                labelHome_Kelompok03MouseMoved(evt);
            }
        });
        labelHome_Kelompok03.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelHome_Kelompok03MouseClicked(evt);
            }
        });
        panel_Kelompok03.add(labelHome_Kelompok03, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 28, -1, -1));

        labelBahanBaku_Kelompok03.setFont(new java.awt.Font("Urbanist", 1, 20)); // NOI18N
        labelBahanBaku_Kelompok03.setForeground(new java.awt.Color(255, 255, 255));
        labelBahanBaku_Kelompok03.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelBahanBaku_Kelompok03.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Icon Bahan Baku Putih.png"))); // NOI18N
        labelBahanBaku_Kelompok03.setText("Bahan Baku");
        labelBahanBaku_Kelompok03.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelBahanBaku_Kelompok03.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                labelBahanBaku_Kelompok03MouseMoved(evt);
            }
        });
        labelBahanBaku_Kelompok03.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelBahanBaku_Kelompok03MouseClicked(evt);
            }
        });
        panel_Kelompok03.add(labelBahanBaku_Kelompok03, new org.netbeans.lib.awtextra.AbsoluteConstraints(446, 28, -1, -1));

        labelBarang_Kelompok03.setBackground(new java.awt.Color(102, 102, 102));
        labelBarang_Kelompok03.setFont(new java.awt.Font("Urbanist", 1, 20)); // NOI18N
        labelBarang_Kelompok03.setForeground(new java.awt.Color(255, 255, 255));
        labelBarang_Kelompok03.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Icon Barang Putih.png"))); // NOI18N
        labelBarang_Kelompok03.setText("Barang");
        labelBarang_Kelompok03.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelBarang_Kelompok03.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                labelBarang_Kelompok03MouseMoved(evt);
            }
        });
        labelBarang_Kelompok03.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelBarang_Kelompok03MouseClicked(evt);
            }
        });
        panel_Kelompok03.add(labelBarang_Kelompok03, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 28, -1, -1));

        labelPelanggan_Kelompok03.setFont(new java.awt.Font("Urbanist", 1, 20)); // NOI18N
        labelPelanggan_Kelompok03.setForeground(new java.awt.Color(255, 255, 255));
        labelPelanggan_Kelompok03.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Icon Pelanggan Home Putih.png"))); // NOI18N
        labelPelanggan_Kelompok03.setText("Pelanggan");
        labelPelanggan_Kelompok03.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelPelanggan_Kelompok03.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                labelPelanggan_Kelompok03MouseMoved(evt);
            }
        });
        labelPelanggan_Kelompok03.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelPelanggan_Kelompok03MouseClicked(evt);
            }
        });
        panel_Kelompok03.add(labelPelanggan_Kelompok03, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 28, -1, -1));

        labelKeluar_Kelompok03.setFont(new java.awt.Font("Urbanist", 1, 20)); // NOI18N
        labelKeluar_Kelompok03.setForeground(new java.awt.Color(255, 255, 255));
        labelKeluar_Kelompok03.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Icon Keluar Putih.png"))); // NOI18N
        labelKeluar_Kelompok03.setText("Keluar");
        labelKeluar_Kelompok03.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelKeluar_Kelompok03.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                labelKeluar_Kelompok03MouseMoved(evt);
            }
        });
        labelKeluar_Kelompok03.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelKeluar_Kelompok03MouseClicked(evt);
            }
        });
        panel_Kelompok03.add(labelKeluar_Kelompok03, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 28, -1, -1));

        labelTransaksi_Kelompok03.setFont(new java.awt.Font("Urbanist", 1, 20)); // NOI18N
        labelTransaksi_Kelompok03.setForeground(new java.awt.Color(255, 255, 255));
        labelTransaksi_Kelompok03.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Icon Transaksi Putih.png"))); // NOI18N
        labelTransaksi_Kelompok03.setText("Transaksi");
        labelTransaksi_Kelompok03.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelTransaksi_Kelompok03.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                labelTransaksi_Kelompok03MouseMoved(evt);
            }
        });
        labelTransaksi_Kelompok03.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelTransaksi_Kelompok03MouseClicked(evt);
            }
        });
        panel_Kelompok03.add(labelTransaksi_Kelompok03, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 28, -1, -1));

        panelGaris_Kelompok03.setBackground(new java.awt.Color(255, 255, 255));
        panel_Kelompok03.add(panelGaris_Kelompok03, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 1280, 5));

        labelSilahkanPesan_Kelompok03.setFont(new java.awt.Font("Urbanist Black", 1, 42)); // NOI18N
        labelSilahkanPesan_Kelompok03.setForeground(new java.awt.Color(21, 0, 53));
        labelSilahkanPesan_Kelompok03.setText("Di Aplikasi Admin");
        panel_Kelompok03.add(labelSilahkanPesan_Kelompok03, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, -1, -1));

        labelKet1_Kelompok03.setFont(new java.awt.Font("Urbanist", 1, 30)); // NOI18N
        labelKet1_Kelompok03.setForeground(new java.awt.Color(21, 0, 53));
        labelKet1_Kelompok03.setText("Selamat Datang");
        panel_Kelompok03.add(labelKet1_Kelompok03, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, -1, -1));

        labelKet2_Kelompok03.setFont(new java.awt.Font("Urbanist", 1, 18)); // NOI18N
        labelKet2_Kelompok03.setForeground(new java.awt.Color(255, 255, 255));
        labelKet2_Kelompok03.setText("Tempat untuk mengecek data pelanggan, bahan baku, dan");
        panel_Kelompok03.add(labelKet2_Kelompok03, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, 530, -1));

        labelKet3_Kelompok03.setFont(new java.awt.Font("Urbanist", 1, 18)); // NOI18N
        labelKet3_Kelompok03.setForeground(new java.awt.Color(255, 255, 255));
        labelKet3_Kelompok03.setText("barang serta transaksi. Juga untuk mencetak laporan data");
        panel_Kelompok03.add(labelKet3_Kelompok03, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 360, 490, -1));

        panelDataBarang_Kelompok03.setBackground(new java.awt.Color(255, 255, 255));
        panelDataBarang_Kelompok03.setRoundBottomLeft(35);
        panelDataBarang_Kelompok03.setRoundBottomRight(35);
        panelDataBarang_Kelompok03.setRoundTopLeft(35);
        panelDataBarang_Kelompok03.setRoundTopRight(35);
        panelDataBarang_Kelompok03.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                panelDataBarang_Kelompok03MouseMoved(evt);
            }
        });
        panelDataBarang_Kelompok03.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelDataBarang_Kelompok03.setBackground(new java.awt.Color(102, 102, 102));
        labelDataBarang_Kelompok03.setFont(new java.awt.Font("Urbanist", 1, 18)); // NOI18N
        labelDataBarang_Kelompok03.setForeground(new java.awt.Color(21, 0, 53));
        labelDataBarang_Kelompok03.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelDataBarang_Kelompok03.setText("Data Barang");
        labelDataBarang_Kelompok03.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelDataBarang_Kelompok03.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                labelDataBarang_Kelompok03MouseMoved(evt);
            }
        });
        labelDataBarang_Kelompok03.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelDataBarang_Kelompok03MouseClicked(evt);
            }
        });
        panelDataBarang_Kelompok03.add(labelDataBarang_Kelompok03, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 15, 220, 30));

        panel_Kelompok03.add(panelDataBarang_Kelompok03, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 400, 225, 60));

        panelDataPelanggan_Kelompok03.setBackground(new java.awt.Color(255, 255, 255));
        panelDataPelanggan_Kelompok03.setRoundBottomLeft(35);
        panelDataPelanggan_Kelompok03.setRoundBottomRight(35);
        panelDataPelanggan_Kelompok03.setRoundTopLeft(35);
        panelDataPelanggan_Kelompok03.setRoundTopRight(35);
        panelDataPelanggan_Kelompok03.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                panelDataPelanggan_Kelompok03MouseMoved(evt);
            }
        });
        panelDataPelanggan_Kelompok03.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelDataPelanggan_Kelompok03.setBackground(new java.awt.Color(102, 102, 102));
        labelDataPelanggan_Kelompok03.setFont(new java.awt.Font("Urbanist", 1, 18)); // NOI18N
        labelDataPelanggan_Kelompok03.setForeground(new java.awt.Color(21, 0, 53));
        labelDataPelanggan_Kelompok03.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelDataPelanggan_Kelompok03.setText("Data Pelanggan");
        labelDataPelanggan_Kelompok03.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelDataPelanggan_Kelompok03.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                labelDataPelanggan_Kelompok03MouseMoved(evt);
            }
        });
        labelDataPelanggan_Kelompok03.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelDataPelanggan_Kelompok03MouseClicked(evt);
            }
        });
        panelDataPelanggan_Kelompok03.add(labelDataPelanggan_Kelompok03, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 15, 220, 30));

        panel_Kelompok03.add(panelDataPelanggan_Kelompok03, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 480, 225, 60));

        panelDataBahanBaku_Kelompok03.setBackground(new java.awt.Color(21, 0, 53));
        panelDataBahanBaku_Kelompok03.setRoundBottomLeft(35);
        panelDataBahanBaku_Kelompok03.setRoundBottomRight(35);
        panelDataBahanBaku_Kelompok03.setRoundTopLeft(35);
        panelDataBahanBaku_Kelompok03.setRoundTopRight(35);
        panelDataBahanBaku_Kelompok03.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                panelDataBahanBaku_Kelompok03MouseMoved(evt);
            }
        });
        panelDataBahanBaku_Kelompok03.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelDataBahanBaku_Kelompok03.setFont(new java.awt.Font("Urbanist", 1, 18)); // NOI18N
        labelDataBahanBaku_Kelompok03.setForeground(new java.awt.Color(255, 255, 255));
        labelDataBahanBaku_Kelompok03.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelDataBahanBaku_Kelompok03.setText("Data Bahan Baku");
        labelDataBahanBaku_Kelompok03.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelDataBahanBaku_Kelompok03.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                labelDataBahanBaku_Kelompok03MouseMoved(evt);
            }
        });
        labelDataBahanBaku_Kelompok03.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelDataBahanBaku_Kelompok03MouseClicked(evt);
            }
        });
        panelDataBahanBaku_Kelompok03.add(labelDataBahanBaku_Kelompok03, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 15, 210, 30));

        panel_Kelompok03.add(panelDataBahanBaku_Kelompok03, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 400, 225, 60));

        panelDataTransaksi_Kelompok03.setBackground(new java.awt.Color(21, 0, 53));
        panelDataTransaksi_Kelompok03.setRoundBottomLeft(35);
        panelDataTransaksi_Kelompok03.setRoundBottomRight(35);
        panelDataTransaksi_Kelompok03.setRoundTopLeft(35);
        panelDataTransaksi_Kelompok03.setRoundTopRight(35);
        panelDataTransaksi_Kelompok03.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                panelDataTransaksi_Kelompok03MouseMoved(evt);
            }
        });
        panelDataTransaksi_Kelompok03.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelDataTransaksi_Kelompok03.setFont(new java.awt.Font("Urbanist", 1, 18)); // NOI18N
        labelDataTransaksi_Kelompok03.setForeground(new java.awt.Color(255, 255, 255));
        labelDataTransaksi_Kelompok03.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelDataTransaksi_Kelompok03.setText("Data Transaksi");
        labelDataTransaksi_Kelompok03.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelDataTransaksi_Kelompok03.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                labelDataTransaksi_Kelompok03MouseMoved(evt);
            }
        });
        labelDataTransaksi_Kelompok03.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelDataTransaksi_Kelompok03MouseClicked(evt);
            }
        });
        panelDataTransaksi_Kelompok03.add(labelDataTransaksi_Kelompok03, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 15, 210, 30));

        panel_Kelompok03.add(panelDataTransaksi_Kelompok03, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 480, 225, 60));

        labelGambar_Kelompok03.setFont(new java.awt.Font("Urbanist", 1, 18)); // NOI18N
        labelGambar_Kelompok03.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Form Home Admin.png"))); // NOI18N
        labelGambar_Kelompok03.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                labelGambar_Kelompok03MouseMoved(evt);
            }
        });
        panel_Kelompok03.add(labelGambar_Kelompok03, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 5, 1270, 710));

        getContentPane().add(panel_Kelompok03, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        setSize(new java.awt.Dimension(1296, 759));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void labelBahanBaku_Kelompok03MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelBahanBaku_Kelompok03MouseMoved
        // TODO add your handling code here:
        labelBahanBaku_Kelompok03.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Icon Bahan Baku.png")));
        labelBahanBaku_Kelompok03.setForeground(new java.awt.Color(21, 0, 53));
    }//GEN-LAST:event_labelBahanBaku_Kelompok03MouseMoved

    private void labelHome_Kelompok03MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelHome_Kelompok03MouseMoved
        // TODO add your handling code here:
        labelHome_Kelompok03.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Icon Home Putih.png")));
        labelHome_Kelompok03.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_labelHome_Kelompok03MouseMoved

    private void labelBarang_Kelompok03MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelBarang_Kelompok03MouseMoved
        // TODO add your handling code here:
        labelBarang_Kelompok03.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Icon Barang.png")));
        labelBarang_Kelompok03.setForeground(new java.awt.Color(21, 0, 53));
    }//GEN-LAST:event_labelBarang_Kelompok03MouseMoved

    private void labelPelanggan_Kelompok03MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelPelanggan_Kelompok03MouseMoved
        // TODO add your handling code here:
        labelPelanggan_Kelompok03.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Icon Pelanggan Home.png")));
        labelPelanggan_Kelompok03.setForeground(new java.awt.Color(21, 0, 53));
    }//GEN-LAST:event_labelPelanggan_Kelompok03MouseMoved

    private void labelTransaksi_Kelompok03MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelTransaksi_Kelompok03MouseMoved
        // TODO add your handling code here:
        labelTransaksi_Kelompok03.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Icon Transaksi.png")));
        labelTransaksi_Kelompok03.setForeground(new java.awt.Color(21, 0, 53));
    }//GEN-LAST:event_labelTransaksi_Kelompok03MouseMoved

    private void labelKeluar_Kelompok03MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelKeluar_Kelompok03MouseMoved
        // TODO add your handling code here:
        labelKeluar_Kelompok03.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Icon Keluar.png")));
        labelKeluar_Kelompok03.setForeground(new java.awt.Color(21, 0, 53));
    }//GEN-LAST:event_labelKeluar_Kelompok03MouseMoved

    private void labelKeluar_Kelompok03MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelKeluar_Kelompok03MouseClicked
        // TODO add your handling code here:
        FormLoginAdmin s = new FormLoginAdmin();
        s.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_labelKeluar_Kelompok03MouseClicked

    private void panelDataBarang_Kelompok03MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelDataBarang_Kelompok03MouseMoved
        // TODO add your handling code here:
        panelDataBarang_Kelompok03.setBackground(new java.awt.Color(57,161,255));
    }//GEN-LAST:event_panelDataBarang_Kelompok03MouseMoved

    private void panelDataBahanBaku_Kelompok03MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelDataBahanBaku_Kelompok03MouseMoved
        // TODO add your handling code here:
        panelDataBahanBaku_Kelompok03.setBackground(new java.awt.Color(57,161,255));
        labelDataBahanBaku_Kelompok03.setForeground(new java.awt.Color(21, 0, 53));
    }//GEN-LAST:event_panelDataBahanBaku_Kelompok03MouseMoved

    private void labelDataBahanBaku_Kelompok03MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelDataBahanBaku_Kelompok03MouseMoved
        // TODO add your handling code here:
        labelDataBahanBaku_Kelompok03.setForeground(new java.awt.Color(21, 0, 53));
        panelDataBahanBaku_Kelompok03.setBackground(new java.awt.Color(57,161,255));
    }//GEN-LAST:event_labelDataBahanBaku_Kelompok03MouseMoved

    private void labelBahanBaku_Kelompok03MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelBahanBaku_Kelompok03MouseClicked
        // TODO add your handling code here:
        FormBahanBakuAdmin s = new FormBahanBakuAdmin();
        s.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_labelBahanBaku_Kelompok03MouseClicked

    private void labelBarang_Kelompok03MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelBarang_Kelompok03MouseClicked
        // TODO add your handling code here:
        FormBarangAdmin s = new FormBarangAdmin();
        s.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_labelBarang_Kelompok03MouseClicked

    private void labelPelanggan_Kelompok03MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelPelanggan_Kelompok03MouseClicked
        // TODO add your handling code here:
        FormPelangganAdmin s = new FormPelangganAdmin();
        s.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_labelPelanggan_Kelompok03MouseClicked

    private void labelTransaksi_Kelompok03MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelTransaksi_Kelompok03MouseClicked
        // TODO add your handling code here:
        FormTransaksiAdmin s = new FormTransaksiAdmin();
        s.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_labelTransaksi_Kelompok03MouseClicked

    private void labelHome_Kelompok03MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelHome_Kelompok03MouseClicked
        // TODO add your handling code here:
        FormHomeAdmin s = new FormHomeAdmin();
        s.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_labelHome_Kelompok03MouseClicked

    private void labelDataBarang_Kelompok03MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelDataBarang_Kelompok03MouseClicked
        // TODO add your handling code here:
        FormBarangAdmin s = new FormBarangAdmin();
        s.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_labelDataBarang_Kelompok03MouseClicked

    private void labelDataBahanBaku_Kelompok03MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelDataBahanBaku_Kelompok03MouseClicked
        // TODO add your handling code here:
        FormBahanBakuAdmin s = new FormBahanBakuAdmin();
        s.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_labelDataBahanBaku_Kelompok03MouseClicked

    private void labelGambar_Kelompok03MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelGambar_Kelompok03MouseMoved
        // TODO add your handling code here:
        labelBahanBaku_Kelompok03.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Icon Bahan Baku Putih.png")));
        labelBahanBaku_Kelompok03.setForeground(new java.awt.Color(255, 255, 255));
        labelHome_Kelompok03.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Icon Home.png")));
        labelHome_Kelompok03.setForeground(new java.awt.Color(21, 0, 53));
        labelBarang_Kelompok03.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Icon Barang Putih.png")));
        labelBarang_Kelompok03.setForeground(new java.awt.Color(255, 255, 255));
        labelPelanggan_Kelompok03.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Icon Pelanggan Home Putih.png")));
        labelPelanggan_Kelompok03.setForeground(new java.awt.Color(255, 255, 255));
        labelTransaksi_Kelompok03.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Icon Transaksi Putih.png")));
        labelTransaksi_Kelompok03.setForeground(new java.awt.Color(255, 255, 255));
        labelKeluar_Kelompok03.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Icon Keluar Putih.png")));
        labelKeluar_Kelompok03.setForeground(new java.awt.Color(255, 255, 255));
        panelDataBarang_Kelompok03.setBackground(new java.awt.Color(255, 255, 255));
        panelDataPelanggan_Kelompok03.setBackground(new java.awt.Color(255, 255, 255));
        panelDataBahanBaku_Kelompok03.setBackground(new java.awt.Color(21, 0, 53));
        labelDataBahanBaku_Kelompok03.setForeground(new java.awt.Color(255, 255, 255));
        panelDataTransaksi_Kelompok03.setBackground(new java.awt.Color(21, 0, 53));
        labelDataTransaksi_Kelompok03.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_labelGambar_Kelompok03MouseMoved

    private void labelDataPelanggan_Kelompok03MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelDataPelanggan_Kelompok03MouseClicked
        // TODO add your handling code here:
        FormPelangganAdmin s = new FormPelangganAdmin();
        s.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_labelDataPelanggan_Kelompok03MouseClicked

    private void panelDataPelanggan_Kelompok03MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelDataPelanggan_Kelompok03MouseMoved
        // TODO add your handling code here:
        
    }//GEN-LAST:event_panelDataPelanggan_Kelompok03MouseMoved

    private void labelDataTransaksi_Kelompok03MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelDataTransaksi_Kelompok03MouseMoved
        // TODO add your handling code here:
        labelDataTransaksi_Kelompok03.setForeground(new java.awt.Color(21, 0, 53));
        panelDataTransaksi_Kelompok03.setBackground(new java.awt.Color(57,161,255));
    }//GEN-LAST:event_labelDataTransaksi_Kelompok03MouseMoved

    private void labelDataTransaksi_Kelompok03MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelDataTransaksi_Kelompok03MouseClicked
        // TODO add your handling code here:
        FormTransaksiAdmin s = new FormTransaksiAdmin();
        s.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_labelDataTransaksi_Kelompok03MouseClicked

    private void panelDataTransaksi_Kelompok03MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelDataTransaksi_Kelompok03MouseMoved
        // TODO add your handling code here:
        labelDataTransaksi_Kelompok03.setForeground(new java.awt.Color(21, 0, 53));
        panelDataTransaksi_Kelompok03.setBackground(new java.awt.Color(57,161,255));
    }//GEN-LAST:event_panelDataTransaksi_Kelompok03MouseMoved

    private void labelDataBarang_Kelompok03MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelDataBarang_Kelompok03MouseMoved
        // TODO add your handling code here:
        panelDataBarang_Kelompok03.setBackground(new java.awt.Color(57,161,255));
    }//GEN-LAST:event_labelDataBarang_Kelompok03MouseMoved

    private void labelDataPelanggan_Kelompok03MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelDataPelanggan_Kelompok03MouseMoved
        // TODO add your handling code here:
        panelDataPelanggan_Kelompok03.setBackground(new java.awt.Color(57,161,255));
    }//GEN-LAST:event_labelDataPelanggan_Kelompok03MouseMoved

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormHomeAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormHomeAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormHomeAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormHomeAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormHomeAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel labelBahanBaku_Kelompok03;
    private javax.swing.JLabel labelBarang_Kelompok03;
    private javax.swing.JLabel labelCartin_Kelompok03;
    private javax.swing.JLabel labelDataBahanBaku_Kelompok03;
    private javax.swing.JLabel labelDataBarang_Kelompok03;
    private javax.swing.JLabel labelDataPelanggan_Kelompok03;
    private javax.swing.JLabel labelDataTransaksi_Kelompok03;
    private javax.swing.JLabel labelFood_Kelompok03;
    private javax.swing.JLabel labelGambar_Kelompok03;
    private javax.swing.JLabel labelHome_Kelompok03;
    private javax.swing.JLabel labelKeluar_Kelompok03;
    private javax.swing.JLabel labelKet1_Kelompok03;
    private javax.swing.JLabel labelKet2_Kelompok03;
    private javax.swing.JLabel labelKet3_Kelompok03;
    private javax.swing.JLabel labelPelanggan_Kelompok03;
    private javax.swing.JLabel labelSilahkanPesan_Kelompok03;
    private javax.swing.JLabel labelTransaksi_Kelompok03;
    private ClassForGUI.PanelRound panelDataBahanBaku_Kelompok03;
    private ClassForGUI.PanelRound panelDataBarang_Kelompok03;
    private ClassForGUI.PanelRound panelDataPelanggan_Kelompok03;
    private ClassForGUI.PanelRound panelDataTransaksi_Kelompok03;
    private ClassForGUI.PanelRound panelGaris_Kelompok03;
    private javax.swing.JPanel panel_Kelompok03;
    // End of variables declaration//GEN-END:variables
}
