/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FormGUI;

/**
 *
 * @author Muhammad Dila
 */
public class FormMenu extends javax.swing.JFrame {

    /**
     * Creates new form FormLogin
     */
    public FormMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_Kelompok03 = new javax.swing.JPanel();
        labelCartin_Kelompok03 = new javax.swing.JLabel();
        labelFood_Kelompok03 = new javax.swing.JLabel();
        labelHome_Kelompok03 = new javax.swing.JLabel();
        labelMenu_Kelompok03 = new javax.swing.JLabel();
        labelLayanan_Kelompok03 = new javax.swing.JLabel();
        labelKeranjang_Kelompok03 = new javax.swing.JLabel();
        labelAkun_Kelompok03 = new javax.swing.JLabel();
        labelKeluar_Kelompok03 = new javax.swing.JLabel();
        labelPembayaran_Kelompok03 = new javax.swing.JLabel();
        panelGaris_Kelompok03 = new ClassForGUI.PanelRound();
        panelDrink_Kelompok03 = new ClassForGUI.PanelRound();
        labelKet5_Kelompok03 = new javax.swing.JLabel();
        labelKet6_Kelompok03 = new javax.swing.JLabel();
        labelKet7_Kelompok03 = new javax.swing.JLabel();
        panelLihatDetailDrink_Kelompok03 = new ClassForGUI.PanelRound();
        labelLihatDetailDrink_Kelompok03 = new javax.swing.JLabel();
        panelGmbr2_Kelompok03 = new ClassForGUI.PanelRound();
        labelpanelGmbr2_Kelompok03 = new javax.swing.JLabel();
        panelGmbr_Kelompok03 = new ClassForGUI.PanelRound();
        labelGmbr_Kelompok03 = new javax.swing.JLabel();
        panelFood_Kelompok03 = new ClassForGUI.PanelRound();
        labelKet_Kelompok03 = new javax.swing.JLabel();
        labelKet2_Kelompok03 = new javax.swing.JLabel();
        labelKet3_Kelompok03 = new javax.swing.JLabel();
        panelLihatDetailFood_Kelompok03 = new ClassForGUI.PanelRound();
        labelDetailFood_Kelompok03 = new javax.swing.JLabel();
        labelGambar_Kelompok03 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_Kelompok03.setBackground(new java.awt.Color(57, 161, 255));
        panel_Kelompok03.setPreferredSize(new java.awt.Dimension(1280, 720));
        panel_Kelompok03.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelCartin_Kelompok03.setFont(new java.awt.Font("Urbanist Black", 1, 24)); // NOI18N
        labelCartin_Kelompok03.setForeground(new java.awt.Color(255, 255, 255));
        labelCartin_Kelompok03.setText("CARTIN");
        labelCartin_Kelompok03.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panel_Kelompok03.add(labelCartin_Kelompok03, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 25, 170, -1));

        labelFood_Kelompok03.setFont(new java.awt.Font("Urbanist Black", 1, 24)); // NOI18N
        labelFood_Kelompok03.setForeground(new java.awt.Color(255, 176, 0));
        labelFood_Kelompok03.setText("FOOD");
        panel_Kelompok03.add(labelFood_Kelompok03, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 25, -1, -1));

        labelHome_Kelompok03.setFont(new java.awt.Font("Urbanist", 1, 20)); // NOI18N
        labelHome_Kelompok03.setForeground(new java.awt.Color(255, 255, 255));
        labelHome_Kelompok03.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Icon Home Putih.png"))); // NOI18N
        labelHome_Kelompok03.setText("Home");
        labelHome_Kelompok03.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelHome_Kelompok03.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                labelHome_Kelompok03MouseMoved(evt);
            }
        });
        labelHome_Kelompok03.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelHome_Kelompok03MouseClicked(evt);
            }
        });
        panel_Kelompok03.add(labelHome_Kelompok03, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 28, -1, -1));

        labelMenu_Kelompok03.setFont(new java.awt.Font("Urbanist", 1, 20)); // NOI18N
        labelMenu_Kelompok03.setForeground(new java.awt.Color(21, 0, 53));
        labelMenu_Kelompok03.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelMenu_Kelompok03.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Icon Menu.png"))); // NOI18N
        labelMenu_Kelompok03.setText("Menu");
        labelMenu_Kelompok03.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelMenu_Kelompok03.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                labelMenu_Kelompok03MouseMoved(evt);
            }
        });
        labelMenu_Kelompok03.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelMenu_Kelompok03MouseClicked(evt);
            }
        });
        panel_Kelompok03.add(labelMenu_Kelompok03, new org.netbeans.lib.awtextra.AbsoluteConstraints(446, 28, -1, -1));

        labelLayanan_Kelompok03.setBackground(new java.awt.Color(102, 102, 102));
        labelLayanan_Kelompok03.setFont(new java.awt.Font("Urbanist", 1, 20)); // NOI18N
        labelLayanan_Kelompok03.setForeground(new java.awt.Color(255, 255, 255));
        labelLayanan_Kelompok03.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Icon Layanan Putih.png"))); // NOI18N
        labelLayanan_Kelompok03.setText("Layanan");
        labelLayanan_Kelompok03.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelLayanan_Kelompok03.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                labelLayanan_Kelompok03MouseMoved(evt);
            }
        });
        labelLayanan_Kelompok03.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelLayanan_Kelompok03MouseClicked(evt);
            }
        });
        panel_Kelompok03.add(labelLayanan_Kelompok03, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 28, -1, -1));

        labelKeranjang_Kelompok03.setFont(new java.awt.Font("Urbanist", 1, 20)); // NOI18N
        labelKeranjang_Kelompok03.setForeground(new java.awt.Color(255, 255, 255));
        labelKeranjang_Kelompok03.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Icon Keranjang Putih.png"))); // NOI18N
        labelKeranjang_Kelompok03.setText("Keranjang");
        labelKeranjang_Kelompok03.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelKeranjang_Kelompok03.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                labelKeranjang_Kelompok03MouseMoved(evt);
            }
        });
        labelKeranjang_Kelompok03.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelKeranjang_Kelompok03MouseClicked(evt);
            }
        });
        panel_Kelompok03.add(labelKeranjang_Kelompok03, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 28, -1, -1));

        labelAkun_Kelompok03.setFont(new java.awt.Font("Urbanist", 1, 20)); // NOI18N
        labelAkun_Kelompok03.setForeground(new java.awt.Color(255, 255, 255));
        labelAkun_Kelompok03.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Icon Akun Putih.png"))); // NOI18N
        labelAkun_Kelompok03.setText("Profile");
        labelAkun_Kelompok03.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelAkun_Kelompok03.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                labelAkun_Kelompok03MouseMoved(evt);
            }
        });
        labelAkun_Kelompok03.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelAkun_Kelompok03MouseClicked(evt);
            }
        });
        panel_Kelompok03.add(labelAkun_Kelompok03, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 28, -1, -1));

        labelKeluar_Kelompok03.setFont(new java.awt.Font("Urbanist", 1, 20)); // NOI18N
        labelKeluar_Kelompok03.setForeground(new java.awt.Color(255, 255, 255));
        labelKeluar_Kelompok03.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Icon Keluar Putih.png"))); // NOI18N
        labelKeluar_Kelompok03.setText("Keluar");
        labelKeluar_Kelompok03.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelKeluar_Kelompok03.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                labelKeluar_Kelompok03MouseMoved(evt);
            }
        });
        labelKeluar_Kelompok03.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelKeluar_Kelompok03MouseClicked(evt);
            }
        });
        panel_Kelompok03.add(labelKeluar_Kelompok03, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 28, -1, -1));

        labelPembayaran_Kelompok03.setFont(new java.awt.Font("Urbanist", 1, 20)); // NOI18N
        labelPembayaran_Kelompok03.setForeground(new java.awt.Color(255, 255, 255));
        labelPembayaran_Kelompok03.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Icon Pembayaran Putih.png"))); // NOI18N
        labelPembayaran_Kelompok03.setText("Pembayaran");
        labelPembayaran_Kelompok03.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelPembayaran_Kelompok03.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                labelPembayaran_Kelompok03MouseMoved(evt);
            }
        });
        labelPembayaran_Kelompok03.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelPembayaran_Kelompok03MouseClicked(evt);
            }
        });
        panel_Kelompok03.add(labelPembayaran_Kelompok03, new org.netbeans.lib.awtextra.AbsoluteConstraints(825, 28, -1, -1));

        panelGaris_Kelompok03.setBackground(new java.awt.Color(255, 255, 255));
        panel_Kelompok03.add(panelGaris_Kelompok03, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 1280, 5));

        panelDrink_Kelompok03.setBackground(new java.awt.Color(255, 255, 255));
        panelDrink_Kelompok03.setRoundBottomLeft(25);
        panelDrink_Kelompok03.setRoundBottomRight(25);
        panelDrink_Kelompok03.setRoundTopLeft(25);
        panelDrink_Kelompok03.setRoundTopRight(25);
        panelDrink_Kelompok03.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelKet5_Kelompok03.setFont(new java.awt.Font("Urbanist Black", 1, 42)); // NOI18N
        labelKet5_Kelompok03.setForeground(new java.awt.Color(21, 0, 53));
        labelKet5_Kelompok03.setText("Fresh Cartin Drink");
        panelDrink_Kelompok03.add(labelKet5_Kelompok03, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 35, -1, -1));

        labelKet6_Kelompok03.setFont(new java.awt.Font("Urbanist", 1, 18)); // NOI18N
        labelKet6_Kelompok03.setForeground(new java.awt.Color(21, 0, 53));
        labelKet6_Kelompok03.setText("Minuman yang luar biasa dari seluruh dunia. Minuman buatan tangan untuk ditemukan dan dinikmati.");
        panelDrink_Kelompok03.add(labelKet6_Kelompok03, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 108, 840, -1));

        labelKet7_Kelompok03.setFont(new java.awt.Font("Urbanist", 1, 18)); // NOI18N
        labelKet7_Kelompok03.setForeground(new java.awt.Color(21, 0, 53));
        labelKet7_Kelompok03.setText("Kami senang membuatkan Anda minuman ini.");
        panelDrink_Kelompok03.add(labelKet7_Kelompok03, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 600, -1));

        panelLihatDetailDrink_Kelompok03.setBackground(new java.awt.Color(21, 0, 53));
        panelLihatDetailDrink_Kelompok03.setRoundBottomLeft(35);
        panelLihatDetailDrink_Kelompok03.setRoundBottomRight(35);
        panelLihatDetailDrink_Kelompok03.setRoundTopLeft(35);
        panelLihatDetailDrink_Kelompok03.setRoundTopRight(35);
        panelLihatDetailDrink_Kelompok03.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                panelLihatDetailDrink_Kelompok03MouseMoved(evt);
            }
        });
        panelLihatDetailDrink_Kelompok03.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelLihatDetailDrink_Kelompok03.setFont(new java.awt.Font("Urbanist", 1, 18)); // NOI18N
        labelLihatDetailDrink_Kelompok03.setForeground(new java.awt.Color(255, 255, 255));
        labelLihatDetailDrink_Kelompok03.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelLihatDetailDrink_Kelompok03.setText("Lihat Detail");
        labelLihatDetailDrink_Kelompok03.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelLihatDetailDrink_Kelompok03.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                labelLihatDetailDrink_Kelompok03MouseMoved(evt);
            }
        });
        labelLihatDetailDrink_Kelompok03.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelLihatDetailDrink_Kelompok03MouseClicked(evt);
            }
        });
        panelLihatDetailDrink_Kelompok03.add(labelLihatDetailDrink_Kelompok03, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 15, 210, 30));

        panelDrink_Kelompok03.add(panelLihatDetailDrink_Kelompok03, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 225, 60));

        panel_Kelompok03.add(panelDrink_Kelompok03, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, 910, 270));

        panelGmbr2_Kelompok03.setBackground(new java.awt.Color(21, 0, 53));
        panelGmbr2_Kelompok03.setRoundBottomLeft(25);
        panelGmbr2_Kelompok03.setRoundBottomRight(25);
        panelGmbr2_Kelompok03.setRoundTopLeft(25);
        panelGmbr2_Kelompok03.setRoundTopRight(25);
        panelGmbr2_Kelompok03.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelpanelGmbr2_Kelompok03.setFont(new java.awt.Font("Urbanist", 1, 20)); // NOI18N
        labelpanelGmbr2_Kelompok03.setForeground(new java.awt.Color(21, 0, 53));
        labelpanelGmbr2_Kelompok03.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelpanelGmbr2_Kelompok03.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Icon Drink Menu.png"))); // NOI18N
        panelGmbr2_Kelompok03.add(labelpanelGmbr2_Kelompok03, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 250, 240));

        panel_Kelompok03.add(panelGmbr2_Kelompok03, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 420, 280, 270));

        panelGmbr_Kelompok03.setBackground(new java.awt.Color(21, 0, 53));
        panelGmbr_Kelompok03.setRoundBottomLeft(25);
        panelGmbr_Kelompok03.setRoundBottomRight(25);
        panelGmbr_Kelompok03.setRoundTopLeft(25);
        panelGmbr_Kelompok03.setRoundTopRight(25);
        panelGmbr_Kelompok03.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelGmbr_Kelompok03.setFont(new java.awt.Font("Urbanist", 1, 20)); // NOI18N
        labelGmbr_Kelompok03.setForeground(new java.awt.Color(21, 0, 53));
        labelGmbr_Kelompok03.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelGmbr_Kelompok03.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Icon Baso Tahu Menu.png"))); // NOI18N
        panelGmbr_Kelompok03.add(labelGmbr_Kelompok03, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 250, 240));

        panel_Kelompok03.add(panelGmbr_Kelompok03, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 280, 270));

        panelFood_Kelompok03.setBackground(new java.awt.Color(255, 255, 255));
        panelFood_Kelompok03.setRoundBottomLeft(25);
        panelFood_Kelompok03.setRoundBottomRight(25);
        panelFood_Kelompok03.setRoundTopLeft(25);
        panelFood_Kelompok03.setRoundTopRight(25);
        panelFood_Kelompok03.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelKet_Kelompok03.setFont(new java.awt.Font("Urbanist Black", 1, 42)); // NOI18N
        labelKet_Kelompok03.setForeground(new java.awt.Color(21, 0, 53));
        labelKet_Kelompok03.setText("Fresh Cartin Food");
        panelFood_Kelompok03.add(labelKet_Kelompok03, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 35, -1, -1));

        labelKet2_Kelompok03.setFont(new java.awt.Font("Urbanist", 1, 18)); // NOI18N
        labelKet2_Kelompok03.setForeground(new java.awt.Color(21, 0, 53));
        labelKet2_Kelompok03.setText("Baso tahu kami dibuat dengan bahan bahan sederhana berkualitas tinggi. Jadi semua kebaikan yang ");
        panelFood_Kelompok03.add(labelKet2_Kelompok03, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 108, 840, -1));

        labelKet3_Kelompok03.setFont(new java.awt.Font("Urbanist", 1, 18)); // NOI18N
        labelKet3_Kelompok03.setForeground(new java.awt.Color(21, 0, 53));
        labelKet3_Kelompok03.setText("Anda cicipi adalah makanan asli, enak, dan bergizi.");
        panelFood_Kelompok03.add(labelKet3_Kelompok03, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 660, -1));

        panelLihatDetailFood_Kelompok03.setBackground(new java.awt.Color(21, 0, 53));
        panelLihatDetailFood_Kelompok03.setRoundBottomLeft(35);
        panelLihatDetailFood_Kelompok03.setRoundBottomRight(35);
        panelLihatDetailFood_Kelompok03.setRoundTopLeft(35);
        panelLihatDetailFood_Kelompok03.setRoundTopRight(35);
        panelLihatDetailFood_Kelompok03.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                panelLihatDetailFood_Kelompok03MouseMoved(evt);
            }
        });
        panelLihatDetailFood_Kelompok03.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelDetailFood_Kelompok03.setFont(new java.awt.Font("Urbanist", 1, 18)); // NOI18N
        labelDetailFood_Kelompok03.setForeground(new java.awt.Color(255, 255, 255));
        labelDetailFood_Kelompok03.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelDetailFood_Kelompok03.setText("Lihat Detail");
        labelDetailFood_Kelompok03.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelDetailFood_Kelompok03.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                labelDetailFood_Kelompok03MouseMoved(evt);
            }
        });
        labelDetailFood_Kelompok03.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelDetailFood_Kelompok03MouseClicked(evt);
            }
        });
        panelLihatDetailFood_Kelompok03.add(labelDetailFood_Kelompok03, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 15, 210, 30));

        panelFood_Kelompok03.add(panelLihatDetailFood_Kelompok03, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 225, 60));

        panel_Kelompok03.add(panelFood_Kelompok03, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 110, 910, 270));

        labelGambar_Kelompok03.setFont(new java.awt.Font("Urbanist", 1, 18)); // NOI18N
        labelGambar_Kelompok03.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                labelGambar_Kelompok03MouseMoved(evt);
            }
        });
        panel_Kelompok03.add(labelGambar_Kelompok03, new org.netbeans.lib.awtextra.AbsoluteConstraints(-5, 5, 1280, 720));

        getContentPane().add(panel_Kelompok03, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        setSize(new java.awt.Dimension(1296, 759));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void labelMenu_Kelompok03MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelMenu_Kelompok03MouseMoved
        // TODO add your handling code here:
        labelMenu_Kelompok03.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Icon Menu Putih.png")));
        labelMenu_Kelompok03.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_labelMenu_Kelompok03MouseMoved

    private void labelGambar_Kelompok03MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelGambar_Kelompok03MouseMoved
        // TODO add your handling code here:
        labelMenu_Kelompok03.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Icon Menu.png")));
        labelMenu_Kelompok03.setForeground(new java.awt.Color(21, 0, 53));
        labelHome_Kelompok03.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Icon Home Putih.png")));
        labelHome_Kelompok03.setForeground(new java.awt.Color(255, 255, 255));
        labelLayanan_Kelompok03.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Icon Layanan Putih.png")));
        labelLayanan_Kelompok03.setForeground(new java.awt.Color(255, 255, 255));
        labelKeranjang_Kelompok03.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Icon Keranjang Putih.png")));
        labelKeranjang_Kelompok03.setForeground(new java.awt.Color(255, 255, 255));
        labelPembayaran_Kelompok03.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Icon Pembayaran Putih.png")));
        labelPembayaran_Kelompok03.setForeground(new java.awt.Color(255, 255, 255));
        labelAkun_Kelompok03.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Icon Akun Putih.png")));
        labelAkun_Kelompok03.setForeground(new java.awt.Color(255, 255, 255));
        labelKeluar_Kelompok03.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Icon Keluar Putih.png")));
        labelKeluar_Kelompok03.setForeground(new java.awt.Color(255, 255, 255));
        panelLihatDetailFood_Kelompok03.setBackground(new java.awt.Color(21, 0, 53));
        labelDetailFood_Kelompok03.setForeground(new java.awt.Color(255, 255, 255));
        panelLihatDetailDrink_Kelompok03.setBackground(new java.awt.Color(21, 0, 53));
        labelLihatDetailDrink_Kelompok03.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_labelGambar_Kelompok03MouseMoved

    private void labelHome_Kelompok03MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelHome_Kelompok03MouseMoved
        // TODO add your handling code here:
        labelHome_Kelompok03.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Icon Home.png")));
        labelHome_Kelompok03.setForeground(new java.awt.Color(21, 0, 53));
    }//GEN-LAST:event_labelHome_Kelompok03MouseMoved

    private void labelLayanan_Kelompok03MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelLayanan_Kelompok03MouseMoved
        // TODO add your handling code here:
        labelLayanan_Kelompok03.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Icon Layanan.png")));
        labelLayanan_Kelompok03.setForeground(new java.awt.Color(21, 0, 53));
    }//GEN-LAST:event_labelLayanan_Kelompok03MouseMoved

    private void labelKeranjang_Kelompok03MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelKeranjang_Kelompok03MouseMoved
        // TODO add your handling code here:
        labelKeranjang_Kelompok03.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Icon Keranjang.png")));
        labelKeranjang_Kelompok03.setForeground(new java.awt.Color(21, 0, 53));
    }//GEN-LAST:event_labelKeranjang_Kelompok03MouseMoved

    private void labelPembayaran_Kelompok03MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelPembayaran_Kelompok03MouseMoved
        // TODO add your handling code here:
        labelPembayaran_Kelompok03.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Icon Pembayaran .png")));
        labelPembayaran_Kelompok03.setForeground(new java.awt.Color(21, 0, 53));
    }//GEN-LAST:event_labelPembayaran_Kelompok03MouseMoved

    private void labelAkun_Kelompok03MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelAkun_Kelompok03MouseMoved
        // TODO add your handling code here:
        labelAkun_Kelompok03.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Icon Akun.png")));
        labelAkun_Kelompok03.setForeground(new java.awt.Color(21, 0, 53));
    }//GEN-LAST:event_labelAkun_Kelompok03MouseMoved

    private void labelKeluar_Kelompok03MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelKeluar_Kelompok03MouseMoved
        // TODO add your handling code here:
        labelKeluar_Kelompok03.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Icon Keluar.png")));
        labelKeluar_Kelompok03.setForeground(new java.awt.Color(21, 0, 53));
    }//GEN-LAST:event_labelKeluar_Kelompok03MouseMoved

    private void labelKeluar_Kelompok03MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelKeluar_Kelompok03MouseClicked
        // TODO add your handling code here:
        FormLogin s = new FormLogin();
        s.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_labelKeluar_Kelompok03MouseClicked

    private void panelLihatDetailFood_Kelompok03MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelLihatDetailFood_Kelompok03MouseMoved
        // TODO add your handling code here:
        panelLihatDetailFood_Kelompok03.setBackground(new java.awt.Color(255, 176, 0));
        labelDetailFood_Kelompok03.setForeground(new java.awt.Color(21, 0, 53));
    }//GEN-LAST:event_panelLihatDetailFood_Kelompok03MouseMoved

    private void labelDetailFood_Kelompok03MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelDetailFood_Kelompok03MouseMoved
        // TODO add your handling code here:
        labelDetailFood_Kelompok03.setForeground(new java.awt.Color(21, 0, 53));
        panelLihatDetailFood_Kelompok03.setBackground(new java.awt.Color(255, 176, 0));
    }//GEN-LAST:event_labelDetailFood_Kelompok03MouseMoved

    private void labelAkun_Kelompok03MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelAkun_Kelompok03MouseClicked
        // TODO add your handling code here:
        FormAkun s = new FormAkun();
        s.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_labelAkun_Kelompok03MouseClicked

    private void labelMenu_Kelompok03MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelMenu_Kelompok03MouseClicked
        // TODO add your handling code here:
        FormMenu s = new FormMenu();
        s.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_labelMenu_Kelompok03MouseClicked

    private void labelLayanan_Kelompok03MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelLayanan_Kelompok03MouseClicked
        // TODO add your handling code here:
        FormLayanan s = new FormLayanan();
        s.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_labelLayanan_Kelompok03MouseClicked

    private void labelKeranjang_Kelompok03MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelKeranjang_Kelompok03MouseClicked
        // TODO add your handling code here:
        FormKeranjang s = new FormKeranjang();
        s.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_labelKeranjang_Kelompok03MouseClicked

    private void labelPembayaran_Kelompok03MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelPembayaran_Kelompok03MouseClicked
        // TODO add your handling code here:
        FormPembayaran s = new FormPembayaran();
        s.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_labelPembayaran_Kelompok03MouseClicked

    private void labelHome_Kelompok03MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelHome_Kelompok03MouseClicked
        // TODO add your handling code here:
        FormHome s = new FormHome();
        s.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_labelHome_Kelompok03MouseClicked

    private void labelLihatDetailDrink_Kelompok03MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelLihatDetailDrink_Kelompok03MouseMoved
        // TODO add your handling code here:
        labelLihatDetailDrink_Kelompok03.setForeground(new java.awt.Color(21, 0, 53));
        panelLihatDetailDrink_Kelompok03.setBackground(new java.awt.Color(255, 176, 0));
    }//GEN-LAST:event_labelLihatDetailDrink_Kelompok03MouseMoved

    private void panelLihatDetailDrink_Kelompok03MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelLihatDetailDrink_Kelompok03MouseMoved
        // TODO add your handling code here:
        panelLihatDetailDrink_Kelompok03.setBackground(new java.awt.Color(255, 176, 0));
        labelLihatDetailDrink_Kelompok03.setForeground(new java.awt.Color(21, 0, 53));
    }//GEN-LAST:event_panelLihatDetailDrink_Kelompok03MouseMoved

    private void labelDetailFood_Kelompok03MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelDetailFood_Kelompok03MouseClicked
        // TODO add your handling code here:
        FormMenuFood s = new FormMenuFood();
        s.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_labelDetailFood_Kelompok03MouseClicked

    private void labelLihatDetailDrink_Kelompok03MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelLihatDetailDrink_Kelompok03MouseClicked
        // TODO add your handling code here:
        FormMenuDrink s = new FormMenuDrink();
        s.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_labelLihatDetailDrink_Kelompok03MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel labelAkun_Kelompok03;
    private javax.swing.JLabel labelCartin_Kelompok03;
    private javax.swing.JLabel labelDetailFood_Kelompok03;
    private javax.swing.JLabel labelFood_Kelompok03;
    private javax.swing.JLabel labelGambar_Kelompok03;
    private javax.swing.JLabel labelGmbr_Kelompok03;
    private javax.swing.JLabel labelHome_Kelompok03;
    private javax.swing.JLabel labelKeluar_Kelompok03;
    private javax.swing.JLabel labelKeranjang_Kelompok03;
    private javax.swing.JLabel labelKet2_Kelompok03;
    private javax.swing.JLabel labelKet3_Kelompok03;
    private javax.swing.JLabel labelKet5_Kelompok03;
    private javax.swing.JLabel labelKet6_Kelompok03;
    private javax.swing.JLabel labelKet7_Kelompok03;
    private javax.swing.JLabel labelKet_Kelompok03;
    private javax.swing.JLabel labelLayanan_Kelompok03;
    private javax.swing.JLabel labelLihatDetailDrink_Kelompok03;
    private javax.swing.JLabel labelMenu_Kelompok03;
    private javax.swing.JLabel labelPembayaran_Kelompok03;
    private javax.swing.JLabel labelpanelGmbr2_Kelompok03;
    private ClassForGUI.PanelRound panelDrink_Kelompok03;
    private ClassForGUI.PanelRound panelFood_Kelompok03;
    private ClassForGUI.PanelRound panelGaris_Kelompok03;
    private ClassForGUI.PanelRound panelGmbr2_Kelompok03;
    private ClassForGUI.PanelRound panelGmbr_Kelompok03;
    private ClassForGUI.PanelRound panelLihatDetailDrink_Kelompok03;
    private ClassForGUI.PanelRound panelLihatDetailFood_Kelompok03;
    private javax.swing.JPanel panel_Kelompok03;
    // End of variables declaration//GEN-END:variables
}
