/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FormGUI;

/**
 *
 * @author Muhammad Dila
 */
public class FormHome extends javax.swing.JFrame {

    /**
     * Creates new form FormLogin
     */
    public FormHome() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_Kelompok03 = new javax.swing.JPanel();
        labelCartin_Kelompok03 = new javax.swing.JLabel();
        labelFood_Kelompok03 = new javax.swing.JLabel();
        labelHome_Kelompok03 = new javax.swing.JLabel();
        labelMenu_Kelompok03 = new javax.swing.JLabel();
        labelLayanan_Kelompok03 = new javax.swing.JLabel();
        labelKeranjang_Kelompok03 = new javax.swing.JLabel();
        labelAkun_Kelompok03 = new javax.swing.JLabel();
        labelKeluar_Kelompok03 = new javax.swing.JLabel();
        labelPembayaran_Kelompok03 = new javax.swing.JLabel();
        labelGambarBasoTahu_Kelompok03 = new javax.swing.JLabel();
        panelGaris_Kelompok03 = new ClassForGUI.PanelRound();
        panelEmail_Kelompok03 = new ClassForGUI.PanelRound();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        labelKet4_Kelompok03 = new javax.swing.JLabel();
        labelSilahkanPesan_Kelompok03 = new javax.swing.JLabel();
        labelKet1_Kelompok03 = new javax.swing.JLabel();
        labelKet2_Kelompok03 = new javax.swing.JLabel();
        labelKet3_Kelompok03 = new javax.swing.JLabel();
        panelLihatMenu_Kelompok03 = new ClassForGUI.PanelRound();
        labelLihatMenu_Kelompok03 = new javax.swing.JLabel();
        panelLihatLayanan_Kelompok03 = new ClassForGUI.PanelRound();
        labelLihatLayanan_Kelompok03 = new javax.swing.JLabel();
        labelGambar_Kelompok03 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_Kelompok03.setBackground(new java.awt.Color(57, 161, 255));
        panel_Kelompok03.setPreferredSize(new java.awt.Dimension(1280, 720));
        panel_Kelompok03.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelCartin_Kelompok03.setFont(new java.awt.Font("Urbanist Black", 1, 24)); // NOI18N
        labelCartin_Kelompok03.setForeground(new java.awt.Color(255, 255, 255));
        labelCartin_Kelompok03.setText("CARTIN");
        labelCartin_Kelompok03.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panel_Kelompok03.add(labelCartin_Kelompok03, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 25, 170, -1));

        labelFood_Kelompok03.setFont(new java.awt.Font("Urbanist Black", 1, 24)); // NOI18N
        labelFood_Kelompok03.setForeground(new java.awt.Color(255, 176, 0));
        labelFood_Kelompok03.setText("FOOD");
        panel_Kelompok03.add(labelFood_Kelompok03, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 25, -1, -1));

        labelHome_Kelompok03.setFont(new java.awt.Font("Urbanist", 1, 20)); // NOI18N
        labelHome_Kelompok03.setForeground(new java.awt.Color(21, 0, 53));
        labelHome_Kelompok03.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Icon Home.png"))); // NOI18N
        labelHome_Kelompok03.setText("Home");
        labelHome_Kelompok03.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelHome_Kelompok03.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                labelHome_Kelompok03MouseMoved(evt);
            }
        });
        labelHome_Kelompok03.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelHome_Kelompok03MouseClicked(evt);
            }
        });
        panel_Kelompok03.add(labelHome_Kelompok03, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 28, -1, -1));

        labelMenu_Kelompok03.setFont(new java.awt.Font("Urbanist", 1, 20)); // NOI18N
        labelMenu_Kelompok03.setForeground(new java.awt.Color(255, 255, 255));
        labelMenu_Kelompok03.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelMenu_Kelompok03.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Icon Menu Putih.png"))); // NOI18N
        labelMenu_Kelompok03.setText("Menu");
        labelMenu_Kelompok03.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelMenu_Kelompok03.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                labelMenu_Kelompok03MouseMoved(evt);
            }
        });
        labelMenu_Kelompok03.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelMenu_Kelompok03MouseClicked(evt);
            }
        });
        panel_Kelompok03.add(labelMenu_Kelompok03, new org.netbeans.lib.awtextra.AbsoluteConstraints(446, 28, -1, -1));

        labelLayanan_Kelompok03.setBackground(new java.awt.Color(102, 102, 102));
        labelLayanan_Kelompok03.setFont(new java.awt.Font("Urbanist", 1, 20)); // NOI18N
        labelLayanan_Kelompok03.setForeground(new java.awt.Color(255, 255, 255));
        labelLayanan_Kelompok03.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Icon Layanan Putih.png"))); // NOI18N
        labelLayanan_Kelompok03.setText("Layanan");
        labelLayanan_Kelompok03.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelLayanan_Kelompok03.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                labelLayanan_Kelompok03MouseMoved(evt);
            }
        });
        labelLayanan_Kelompok03.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelLayanan_Kelompok03MouseClicked(evt);
            }
        });
        panel_Kelompok03.add(labelLayanan_Kelompok03, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 28, -1, -1));

        labelKeranjang_Kelompok03.setFont(new java.awt.Font("Urbanist", 1, 20)); // NOI18N
        labelKeranjang_Kelompok03.setForeground(new java.awt.Color(255, 255, 255));
        labelKeranjang_Kelompok03.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Icon Keranjang Putih.png"))); // NOI18N
        labelKeranjang_Kelompok03.setText("Keranjang");
        labelKeranjang_Kelompok03.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelKeranjang_Kelompok03.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                labelKeranjang_Kelompok03MouseMoved(evt);
            }
        });
        labelKeranjang_Kelompok03.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelKeranjang_Kelompok03MouseClicked(evt);
            }
        });
        panel_Kelompok03.add(labelKeranjang_Kelompok03, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 28, -1, -1));

        labelAkun_Kelompok03.setFont(new java.awt.Font("Urbanist", 1, 20)); // NOI18N
        labelAkun_Kelompok03.setForeground(new java.awt.Color(255, 255, 255));
        labelAkun_Kelompok03.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Icon Akun Putih.png"))); // NOI18N
        labelAkun_Kelompok03.setText("Profile");
        labelAkun_Kelompok03.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelAkun_Kelompok03.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                labelAkun_Kelompok03MouseMoved(evt);
            }
        });
        labelAkun_Kelompok03.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelAkun_Kelompok03MouseClicked(evt);
            }
        });
        panel_Kelompok03.add(labelAkun_Kelompok03, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 28, -1, -1));

        labelKeluar_Kelompok03.setFont(new java.awt.Font("Urbanist", 1, 20)); // NOI18N
        labelKeluar_Kelompok03.setForeground(new java.awt.Color(255, 255, 255));
        labelKeluar_Kelompok03.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Icon Keluar Putih.png"))); // NOI18N
        labelKeluar_Kelompok03.setText("Keluar");
        labelKeluar_Kelompok03.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelKeluar_Kelompok03.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                labelKeluar_Kelompok03MouseMoved(evt);
            }
        });
        labelKeluar_Kelompok03.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelKeluar_Kelompok03MouseClicked(evt);
            }
        });
        panel_Kelompok03.add(labelKeluar_Kelompok03, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 28, -1, -1));

        labelPembayaran_Kelompok03.setFont(new java.awt.Font("Urbanist", 1, 20)); // NOI18N
        labelPembayaran_Kelompok03.setForeground(new java.awt.Color(255, 255, 255));
        labelPembayaran_Kelompok03.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Icon Pembayaran Putih.png"))); // NOI18N
        labelPembayaran_Kelompok03.setText("Pembayaran");
        labelPembayaran_Kelompok03.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelPembayaran_Kelompok03.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                labelPembayaran_Kelompok03MouseMoved(evt);
            }
        });
        labelPembayaran_Kelompok03.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelPembayaran_Kelompok03MouseClicked(evt);
            }
        });
        panel_Kelompok03.add(labelPembayaran_Kelompok03, new org.netbeans.lib.awtextra.AbsoluteConstraints(825, 28, -1, -1));

        labelGambarBasoTahu_Kelompok03.setFont(new java.awt.Font("Urbanist", 1, 20)); // NOI18N
        labelGambarBasoTahu_Kelompok03.setForeground(new java.awt.Color(255, 255, 255));
        labelGambarBasoTahu_Kelompok03.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelGambarBasoTahu_Kelompok03.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Form Home.png"))); // NOI18N
        labelGambarBasoTahu_Kelompok03.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        panel_Kelompok03.add(labelGambarBasoTahu_Kelompok03, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 140, 420, 390));

        panelGaris_Kelompok03.setBackground(new java.awt.Color(255, 255, 255));
        panel_Kelompok03.add(panelGaris_Kelompok03, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 1280, 5));

        panelEmail_Kelompok03.setBackground(new java.awt.Color(255, 176, 0));
        panelEmail_Kelompok03.setRoundBottomLeft(25);
        panelEmail_Kelompok03.setRoundBottomRight(25);
        panelEmail_Kelompok03.setRoundTopLeft(25);
        panelEmail_Kelompok03.setRoundTopRight(25);
        panelEmail_Kelompok03.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Urbanist", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(21, 0, 53));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Icon Star.png"))); // NOI18N
        jLabel1.setText("5.0");
        panelEmail_Kelompok03.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, -1, -1));

        jLabel2.setFont(new java.awt.Font("Urbanist Black", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(21, 0, 53));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Rp. 15.000");
        panelEmail_Kelompok03.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 260, -1));

        jLabel3.setFont(new java.awt.Font("Urbanist", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(21, 0, 53));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Baso Tahu Original");
        panelEmail_Kelompok03.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        panel_Kelompok03.add(panelEmail_Kelompok03, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 420, 300, 230));

        labelKet4_Kelompok03.setFont(new java.awt.Font("Urbanist", 1, 18)); // NOI18N
        labelKet4_Kelompok03.setForeground(new java.awt.Color(255, 255, 255));
        labelKet4_Kelompok03.setText("sehat dan bergizi.");
        panel_Kelompok03.add(labelKet4_Kelompok03, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 424, 480, -1));

        labelSilahkanPesan_Kelompok03.setFont(new java.awt.Font("Urbanist Black", 1, 42)); // NOI18N
        labelSilahkanPesan_Kelompok03.setForeground(new java.awt.Color(21, 0, 53));
        labelSilahkanPesan_Kelompok03.setText("Silahkan Pesan");
        panel_Kelompok03.add(labelSilahkanPesan_Kelompok03, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, -1, -1));

        labelKet1_Kelompok03.setFont(new java.awt.Font("Urbanist", 1, 36)); // NOI18N
        labelKet1_Kelompok03.setForeground(new java.awt.Color(21, 0, 53));
        labelKet1_Kelompok03.setText("Baso Tahu Favorit Kamu !!");
        panel_Kelompok03.add(labelKet1_Kelompok03, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 320, -1, -1));

        labelKet2_Kelompok03.setFont(new java.awt.Font("Urbanist", 1, 18)); // NOI18N
        labelKet2_Kelompok03.setForeground(new java.awt.Color(255, 255, 255));
        labelKet2_Kelompok03.setText("Baso tahu Cartin Food merupakan baso tahu yang terbuat");
        panel_Kelompok03.add(labelKet2_Kelompok03, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 380, 480, -1));

        labelKet3_Kelompok03.setFont(new java.awt.Font("Urbanist", 1, 18)); // NOI18N
        labelKet3_Kelompok03.setForeground(new java.awt.Color(255, 255, 255));
        labelKet3_Kelompok03.setText("dari ikan tenggri segar, tanpa bahan pengawet yang pasti");
        panel_Kelompok03.add(labelKet3_Kelompok03, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 402, 480, -1));

        panelLihatMenu_Kelompok03.setBackground(new java.awt.Color(255, 255, 255));
        panelLihatMenu_Kelompok03.setRoundBottomLeft(35);
        panelLihatMenu_Kelompok03.setRoundBottomRight(35);
        panelLihatMenu_Kelompok03.setRoundTopLeft(35);
        panelLihatMenu_Kelompok03.setRoundTopRight(35);
        panelLihatMenu_Kelompok03.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                panelLihatMenu_Kelompok03MouseMoved(evt);
            }
        });
        panelLihatMenu_Kelompok03.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelLihatMenu_Kelompok03.setBackground(new java.awt.Color(102, 102, 102));
        labelLihatMenu_Kelompok03.setFont(new java.awt.Font("Urbanist", 1, 18)); // NOI18N
        labelLihatMenu_Kelompok03.setForeground(new java.awt.Color(21, 0, 53));
        labelLihatMenu_Kelompok03.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelLihatMenu_Kelompok03.setText("Lihat Menu");
        labelLihatMenu_Kelompok03.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelLihatMenu_Kelompok03.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelLihatMenu_Kelompok03MouseClicked(evt);
            }
        });
        panelLihatMenu_Kelompok03.add(labelLihatMenu_Kelompok03, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 15, 220, 30));

        panel_Kelompok03.add(panelLihatMenu_Kelompok03, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 470, 225, 60));

        panelLihatLayanan_Kelompok03.setBackground(new java.awt.Color(21, 0, 53));
        panelLihatLayanan_Kelompok03.setRoundBottomLeft(35);
        panelLihatLayanan_Kelompok03.setRoundBottomRight(35);
        panelLihatLayanan_Kelompok03.setRoundTopLeft(35);
        panelLihatLayanan_Kelompok03.setRoundTopRight(35);
        panelLihatLayanan_Kelompok03.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                panelLihatLayanan_Kelompok03MouseMoved(evt);
            }
        });
        panelLihatLayanan_Kelompok03.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelLihatLayanan_Kelompok03.setFont(new java.awt.Font("Urbanist", 1, 18)); // NOI18N
        labelLihatLayanan_Kelompok03.setForeground(new java.awt.Color(255, 255, 255));
        labelLihatLayanan_Kelompok03.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelLihatLayanan_Kelompok03.setText("Lihat Layanan");
        labelLihatLayanan_Kelompok03.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelLihatLayanan_Kelompok03.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                labelLihatLayanan_Kelompok03MouseMoved(evt);
            }
        });
        labelLihatLayanan_Kelompok03.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelLihatLayanan_Kelompok03MouseClicked(evt);
            }
        });
        panelLihatLayanan_Kelompok03.add(labelLihatLayanan_Kelompok03, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 15, 210, 30));

        panel_Kelompok03.add(panelLihatLayanan_Kelompok03, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 470, 225, 60));

        labelGambar_Kelompok03.setFont(new java.awt.Font("Urbanist", 1, 18)); // NOI18N
        labelGambar_Kelompok03.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Form Home 2.png"))); // NOI18N
        labelGambar_Kelompok03.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                labelGambar_Kelompok03MouseMoved(evt);
            }
        });
        panel_Kelompok03.add(labelGambar_Kelompok03, new org.netbeans.lib.awtextra.AbsoluteConstraints(-5, 5, 1280, 720));

        getContentPane().add(panel_Kelompok03, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        setSize(new java.awt.Dimension(1296, 759));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void labelMenu_Kelompok03MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelMenu_Kelompok03MouseMoved
        // TODO add your handling code here:
        labelMenu_Kelompok03.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Icon Menu.png")));
        labelMenu_Kelompok03.setForeground(new java.awt.Color(21, 0, 53));
    }//GEN-LAST:event_labelMenu_Kelompok03MouseMoved

    private void labelGambar_Kelompok03MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelGambar_Kelompok03MouseMoved
        // TODO add your handling code here:
        labelMenu_Kelompok03.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Icon Menu Putih.png")));
        labelMenu_Kelompok03.setForeground(new java.awt.Color(255, 255, 255));
        labelHome_Kelompok03.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Icon Home.png")));
        labelHome_Kelompok03.setForeground(new java.awt.Color(21, 0, 53));
        labelLayanan_Kelompok03.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Icon Layanan Putih.png")));
        labelLayanan_Kelompok03.setForeground(new java.awt.Color(255, 255, 255));
        labelKeranjang_Kelompok03.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Icon Keranjang Putih.png")));
        labelKeranjang_Kelompok03.setForeground(new java.awt.Color(255, 255, 255));
        labelPembayaran_Kelompok03.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Icon Pembayaran Putih.png")));
        labelPembayaran_Kelompok03.setForeground(new java.awt.Color(255, 255, 255));
        labelAkun_Kelompok03.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Icon Akun Putih.png")));
        labelAkun_Kelompok03.setForeground(new java.awt.Color(255, 255, 255));
        labelKeluar_Kelompok03.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Icon Keluar Putih.png")));
        labelKeluar_Kelompok03.setForeground(new java.awt.Color(255, 255, 255));
        panelLihatMenu_Kelompok03.setBackground(new java.awt.Color(255, 255, 255));
        panelLihatLayanan_Kelompok03.setBackground(new java.awt.Color(21, 0, 53));
        labelLihatLayanan_Kelompok03.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_labelGambar_Kelompok03MouseMoved

    private void labelHome_Kelompok03MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelHome_Kelompok03MouseMoved
        // TODO add your handling code here:
        labelHome_Kelompok03.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Icon Home Putih.png")));
        labelHome_Kelompok03.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_labelHome_Kelompok03MouseMoved

    private void labelLayanan_Kelompok03MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelLayanan_Kelompok03MouseMoved
        // TODO add your handling code here:
        labelLayanan_Kelompok03.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Icon Layanan.png")));
        labelLayanan_Kelompok03.setForeground(new java.awt.Color(21, 0, 53));
    }//GEN-LAST:event_labelLayanan_Kelompok03MouseMoved

    private void labelKeranjang_Kelompok03MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelKeranjang_Kelompok03MouseMoved
        // TODO add your handling code here:
        labelKeranjang_Kelompok03.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Icon Keranjang.png")));
        labelKeranjang_Kelompok03.setForeground(new java.awt.Color(21, 0, 53));
    }//GEN-LAST:event_labelKeranjang_Kelompok03MouseMoved

    private void labelPembayaran_Kelompok03MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelPembayaran_Kelompok03MouseMoved
        // TODO add your handling code here:
        labelPembayaran_Kelompok03.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Icon Pembayaran .png")));
        labelPembayaran_Kelompok03.setForeground(new java.awt.Color(21, 0, 53));
    }//GEN-LAST:event_labelPembayaran_Kelompok03MouseMoved

    private void labelAkun_Kelompok03MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelAkun_Kelompok03MouseMoved
        // TODO add your handling code here:
        labelAkun_Kelompok03.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Icon Akun.png")));
        labelAkun_Kelompok03.setForeground(new java.awt.Color(21, 0, 53));
    }//GEN-LAST:event_labelAkun_Kelompok03MouseMoved

    private void labelKeluar_Kelompok03MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelKeluar_Kelompok03MouseMoved
        // TODO add your handling code here:
        labelKeluar_Kelompok03.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Icon Keluar.png")));
        labelKeluar_Kelompok03.setForeground(new java.awt.Color(21, 0, 53));
    }//GEN-LAST:event_labelKeluar_Kelompok03MouseMoved

    private void labelKeluar_Kelompok03MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelKeluar_Kelompok03MouseClicked
        // TODO add your handling code here:
        FormLogin s = new FormLogin();
        s.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_labelKeluar_Kelompok03MouseClicked

    private void panelLihatMenu_Kelompok03MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelLihatMenu_Kelompok03MouseMoved
        // TODO add your handling code here:
        panelLihatMenu_Kelompok03.setBackground(new java.awt.Color(255, 176, 0));
    }//GEN-LAST:event_panelLihatMenu_Kelompok03MouseMoved

    private void panelLihatLayanan_Kelompok03MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelLihatLayanan_Kelompok03MouseMoved
        // TODO add your handling code here:
        panelLihatLayanan_Kelompok03.setBackground(new java.awt.Color(255, 176, 0));
        labelLihatLayanan_Kelompok03.setForeground(new java.awt.Color(21, 0, 53));
    }//GEN-LAST:event_panelLihatLayanan_Kelompok03MouseMoved

    private void labelLihatLayanan_Kelompok03MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelLihatLayanan_Kelompok03MouseMoved
        // TODO add your handling code here:
        labelLihatLayanan_Kelompok03.setForeground(new java.awt.Color(21, 0, 53));
    }//GEN-LAST:event_labelLihatLayanan_Kelompok03MouseMoved

    private void labelAkun_Kelompok03MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelAkun_Kelompok03MouseClicked
        // TODO add your handling code here:
        FormAkun s = new FormAkun();
        s.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_labelAkun_Kelompok03MouseClicked

    private void labelMenu_Kelompok03MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelMenu_Kelompok03MouseClicked
        // TODO add your handling code here:
        FormMenu s = new FormMenu();
        s.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_labelMenu_Kelompok03MouseClicked

    private void labelLayanan_Kelompok03MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelLayanan_Kelompok03MouseClicked
        // TODO add your handling code here:
        FormLayanan s = new FormLayanan();
        s.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_labelLayanan_Kelompok03MouseClicked

    private void labelKeranjang_Kelompok03MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelKeranjang_Kelompok03MouseClicked
        // TODO add your handling code here:
        FormKeranjang s = new FormKeranjang();
        s.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_labelKeranjang_Kelompok03MouseClicked

    private void labelPembayaran_Kelompok03MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelPembayaran_Kelompok03MouseClicked
        // TODO add your handling code here:
        FormPembayaran s = new FormPembayaran();
        s.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_labelPembayaran_Kelompok03MouseClicked

    private void labelHome_Kelompok03MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelHome_Kelompok03MouseClicked
        // TODO add your handling code here:
        FormHome s = new FormHome();
        s.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_labelHome_Kelompok03MouseClicked

    private void labelLihatMenu_Kelompok03MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelLihatMenu_Kelompok03MouseClicked
        // TODO add your handling code here:
        FormMenu s = new FormMenu();
        s.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_labelLihatMenu_Kelompok03MouseClicked

    private void labelLihatLayanan_Kelompok03MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelLihatLayanan_Kelompok03MouseClicked
        // TODO add your handling code here:
        FormLayanan s = new FormLayanan();
        s.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_labelLihatLayanan_Kelompok03MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel labelAkun_Kelompok03;
    private javax.swing.JLabel labelCartin_Kelompok03;
    private javax.swing.JLabel labelFood_Kelompok03;
    private javax.swing.JLabel labelGambarBasoTahu_Kelompok03;
    private javax.swing.JLabel labelGambar_Kelompok03;
    private javax.swing.JLabel labelHome_Kelompok03;
    private javax.swing.JLabel labelKeluar_Kelompok03;
    private javax.swing.JLabel labelKeranjang_Kelompok03;
    private javax.swing.JLabel labelKet1_Kelompok03;
    private javax.swing.JLabel labelKet2_Kelompok03;
    private javax.swing.JLabel labelKet3_Kelompok03;
    private javax.swing.JLabel labelKet4_Kelompok03;
    private javax.swing.JLabel labelLayanan_Kelompok03;
    private javax.swing.JLabel labelLihatLayanan_Kelompok03;
    private javax.swing.JLabel labelLihatMenu_Kelompok03;
    private javax.swing.JLabel labelMenu_Kelompok03;
    private javax.swing.JLabel labelPembayaran_Kelompok03;
    private javax.swing.JLabel labelSilahkanPesan_Kelompok03;
    private ClassForGUI.PanelRound panelEmail_Kelompok03;
    private ClassForGUI.PanelRound panelGaris_Kelompok03;
    private ClassForGUI.PanelRound panelLihatLayanan_Kelompok03;
    private ClassForGUI.PanelRound panelLihatMenu_Kelompok03;
    private javax.swing.JPanel panel_Kelompok03;
    // End of variables declaration//GEN-END:variables
}
