/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FormGUI;

/**
 *
 * @author Muhammad Dila
 */
public class FormPilihanAplikasi extends javax.swing.JFrame {

    
    public FormPilihanAplikasi() {
        initComponents();
    }

   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_Kelompok03 = new javax.swing.JPanel();
        labelCartin_Kelompok03 = new javax.swing.JLabel();
        labelFood_Kelompok03 = new javax.swing.JLabel();
        labelKet_Kelompok03 = new javax.swing.JLabel();
        panelPelanggan_Kelompok03 = new ClassForGUI.PanelRound();
        labelPelanggan_Kelompok03 = new javax.swing.JLabel();
        panelAdmin_Kelompok03 = new ClassForGUI.PanelRound();
        labelAdmin_Kelompok03 = new javax.swing.JLabel();
        panelGmbrAdmin_Kelompok03 = new ClassForGUI.PanelRound();
        labelGmbrAdmin_Kelompok03 = new javax.swing.JLabel();
        panelGmbrPlg_Kelompok03 = new ClassForGUI.PanelRound();
        GmbrPlg_Kelompok03 = new javax.swing.JLabel();
        labelTentang_Kelompok03 = new javax.swing.JLabel();
        labelGambar_Kelompok03 = new javax.swing.JLabel();
        panelTentang_Kelompok03 = new javax.swing.JPanel();
        labelCartin_Kelompok4 = new javax.swing.JLabel();
        labelFood_Kelompok4 = new javax.swing.JLabel();
        panelNama1_Kelompok03 = new ClassForGUI.PanelRound();
        labelNama2_Kelompok03 = new javax.swing.JLabel();
        panelNama2_Kelompok03 = new ClassForGUI.PanelRound();
        labelNama2_Kelompok4 = new javax.swing.JLabel();
        panelNama3_Kelompok03 = new ClassForGUI.PanelRound();
        labelNama2_Kelompok5 = new javax.swing.JLabel();
        panelNama4_Kelompok03 = new ClassForGUI.PanelRound();
        labelNama2_Kelompok6 = new javax.swing.JLabel();
        panelNama5_Kelompok03 = new ClassForGUI.PanelRound();
        labelNama2_Kelompok7 = new javax.swing.JLabel();
        panelKembali_Kelompok03 = new ClassForGUI.PanelRound();
        labelKembali_Kelompok03 = new javax.swing.JLabel();
        labelGambar1_Kelompok03 = new javax.swing.JLabel();
        labelGambar2_Kelompok03 = new javax.swing.JLabel();
        labelKet_Kelompok5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_Kelompok03.setBackground(new java.awt.Color(57, 161, 255));
        panel_Kelompok03.setPreferredSize(new java.awt.Dimension(1280, 720));
        panel_Kelompok03.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelCartin_Kelompok03.setFont(new java.awt.Font("Urbanist Black", 1, 30)); // NOI18N
        labelCartin_Kelompok03.setForeground(new java.awt.Color(255, 255, 255));
        labelCartin_Kelompok03.setText("CARTIN");
        panel_Kelompok03.add(labelCartin_Kelompok03, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 40, -1, -1));

        labelFood_Kelompok03.setFont(new java.awt.Font("Urbanist Black", 1, 30)); // NOI18N
        labelFood_Kelompok03.setForeground(new java.awt.Color(255, 176, 0));
        labelFood_Kelompok03.setText("FOOD");
        panel_Kelompok03.add(labelFood_Kelompok03, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 40, -1, -1));

        labelKet_Kelompok03.setFont(new java.awt.Font("Urbanist Black", 1, 30)); // NOI18N
        labelKet_Kelompok03.setForeground(new java.awt.Color(21, 0, 53));
        labelKet_Kelompok03.setText("Silahkan Pilih Program Yang Akan Anda Gunakan");
        panel_Kelompok03.add(labelKet_Kelompok03, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, -1, -1));

        panelPelanggan_Kelompok03.setBackground(new java.awt.Color(21, 0, 53));
        panelPelanggan_Kelompok03.setRoundBottomLeft(35);
        panelPelanggan_Kelompok03.setRoundBottomRight(35);
        panelPelanggan_Kelompok03.setRoundTopLeft(35);
        panelPelanggan_Kelompok03.setRoundTopRight(35);
        panelPelanggan_Kelompok03.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                panelPelanggan_Kelompok03MouseMoved(evt);
            }
        });
        panelPelanggan_Kelompok03.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelPelanggan_Kelompok03.setFont(new java.awt.Font("Urbanist", 1, 18)); // NOI18N
        labelPelanggan_Kelompok03.setForeground(new java.awt.Color(255, 255, 255));
        labelPelanggan_Kelompok03.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelPelanggan_Kelompok03.setText("PROGRAM APLIKASI PELANGGAN");
        labelPelanggan_Kelompok03.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelPelanggan_Kelompok03.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                labelPelanggan_Kelompok03MouseMoved(evt);
            }
        });
        labelPelanggan_Kelompok03.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelPelanggan_Kelompok03MouseClicked(evt);
            }
        });
        panelPelanggan_Kelompok03.add(labelPelanggan_Kelompok03, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 15, 430, 30));

        panel_Kelompok03.add(panelPelanggan_Kelompok03, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 580, 450, 60));

        panelAdmin_Kelompok03.setBackground(new java.awt.Color(21, 0, 53));
        panelAdmin_Kelompok03.setRoundBottomLeft(35);
        panelAdmin_Kelompok03.setRoundBottomRight(35);
        panelAdmin_Kelompok03.setRoundTopLeft(35);
        panelAdmin_Kelompok03.setRoundTopRight(35);
        panelAdmin_Kelompok03.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                panelAdmin_Kelompok03MouseMoved(evt);
            }
        });
        panelAdmin_Kelompok03.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelAdmin_Kelompok03.setFont(new java.awt.Font("Urbanist", 1, 18)); // NOI18N
        labelAdmin_Kelompok03.setForeground(new java.awt.Color(255, 255, 255));
        labelAdmin_Kelompok03.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelAdmin_Kelompok03.setText("PROGRAM APLIKASI ADMIN");
        labelAdmin_Kelompok03.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelAdmin_Kelompok03.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                labelAdmin_Kelompok03MouseMoved(evt);
            }
        });
        labelAdmin_Kelompok03.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelAdmin_Kelompok03MouseClicked(evt);
            }
        });
        panelAdmin_Kelompok03.add(labelAdmin_Kelompok03, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 15, 430, 30));

        panel_Kelompok03.add(panelAdmin_Kelompok03, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 580, 450, 60));

        panelGmbrAdmin_Kelompok03.setBackground(new java.awt.Color(255, 176, 0));
        panelGmbrAdmin_Kelompok03.setRoundBottomLeft(25);
        panelGmbrAdmin_Kelompok03.setRoundBottomRight(25);
        panelGmbrAdmin_Kelompok03.setRoundTopLeft(25);
        panelGmbrAdmin_Kelompok03.setRoundTopRight(25);
        panelGmbrAdmin_Kelompok03.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelGmbrAdmin_Kelompok03.setFont(new java.awt.Font("Urbanist", 1, 20)); // NOI18N
        labelGmbrAdmin_Kelompok03.setForeground(new java.awt.Color(21, 0, 53));
        labelGmbrAdmin_Kelompok03.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelGmbrAdmin_Kelompok03.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Icon Admin.png"))); // NOI18N
        panelGmbrAdmin_Kelompok03.add(labelGmbrAdmin_Kelompok03, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 420, 350));

        panel_Kelompok03.add(panelGmbrAdmin_Kelompok03, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 180, 450, 380));

        panelGmbrPlg_Kelompok03.setBackground(new java.awt.Color(255, 255, 255));
        panelGmbrPlg_Kelompok03.setRoundBottomLeft(25);
        panelGmbrPlg_Kelompok03.setRoundBottomRight(25);
        panelGmbrPlg_Kelompok03.setRoundTopLeft(25);
        panelGmbrPlg_Kelompok03.setRoundTopRight(25);
        panelGmbrPlg_Kelompok03.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        GmbrPlg_Kelompok03.setFont(new java.awt.Font("Urbanist", 1, 20)); // NOI18N
        GmbrPlg_Kelompok03.setForeground(new java.awt.Color(21, 0, 53));
        GmbrPlg_Kelompok03.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        GmbrPlg_Kelompok03.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Icon Pelanggan.png"))); // NOI18N
        panelGmbrPlg_Kelompok03.add(GmbrPlg_Kelompok03, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 380));

        panel_Kelompok03.add(panelGmbrPlg_Kelompok03, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, 450, 380));

        labelTentang_Kelompok03.setFont(new java.awt.Font("Urbanist", 1, 18)); // NOI18N
        labelTentang_Kelompok03.setForeground(new java.awt.Color(21, 0, 53));
        labelTentang_Kelompok03.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTentang_Kelompok03.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Icon Help Kuning.png"))); // NOI18N
        labelTentang_Kelompok03.setText("Tentang");
        labelTentang_Kelompok03.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelTentang_Kelompok03.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                labelTentang_Kelompok03MouseMoved(evt);
            }
        });
        labelTentang_Kelompok03.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelTentang_Kelompok03MouseClicked(evt);
            }
        });
        panel_Kelompok03.add(labelTentang_Kelompok03, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 40, -1, -1));

        labelGambar_Kelompok03.setFont(new java.awt.Font("Urbanist", 1, 18)); // NOI18N
        labelGambar_Kelompok03.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelGambar_Kelompok03.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Form Pilihan APK.png"))); // NOI18N
        labelGambar_Kelompok03.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                labelGambar_Kelompok03MouseMoved(evt);
            }
        });
        panel_Kelompok03.add(labelGambar_Kelompok03, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        getContentPane().add(panel_Kelompok03, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        panelTentang_Kelompok03.setBackground(new java.awt.Color(57, 161, 255));
        panelTentang_Kelompok03.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelCartin_Kelompok4.setFont(new java.awt.Font("Urbanist Black", 1, 30)); // NOI18N
        labelCartin_Kelompok4.setForeground(new java.awt.Color(255, 255, 255));
        labelCartin_Kelompok4.setText("CARTIN");
        panelTentang_Kelompok03.add(labelCartin_Kelompok4, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 40, -1, -1));

        labelFood_Kelompok4.setFont(new java.awt.Font("Urbanist Black", 1, 30)); // NOI18N
        labelFood_Kelompok4.setForeground(new java.awt.Color(255, 176, 0));
        labelFood_Kelompok4.setText("FOOD");
        panelTentang_Kelompok03.add(labelFood_Kelompok4, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 40, -1, -1));

        panelNama1_Kelompok03.setBackground(new java.awt.Color(21, 0, 53));
        panelNama1_Kelompok03.setRoundBottomLeft(15);
        panelNama1_Kelompok03.setRoundBottomRight(15);
        panelNama1_Kelompok03.setRoundTopLeft(15);
        panelNama1_Kelompok03.setRoundTopRight(15);
        panelNama1_Kelompok03.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                panelNama1_Kelompok03MouseMoved(evt);
            }
        });
        panelNama1_Kelompok03.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelNama2_Kelompok03.setFont(new java.awt.Font("Urbanist Black", 1, 18)); // NOI18N
        labelNama2_Kelompok03.setForeground(new java.awt.Color(255, 255, 255));
        labelNama2_Kelompok03.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelNama2_Kelompok03.setText("Muhammad Dila");
        panelNama1_Kelompok03.add(labelNama2_Kelompok03, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 170, 30));

        panelTentang_Kelompok03.add(panelNama1_Kelompok03, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 330, 190, 30));

        panelNama2_Kelompok03.setBackground(new java.awt.Color(21, 0, 53));
        panelNama2_Kelompok03.setRoundBottomLeft(15);
        panelNama2_Kelompok03.setRoundBottomRight(15);
        panelNama2_Kelompok03.setRoundTopLeft(15);
        panelNama2_Kelompok03.setRoundTopRight(15);
        panelNama2_Kelompok03.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                panelNama2_Kelompok03MouseMoved(evt);
            }
        });
        panelNama2_Kelompok03.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelNama2_Kelompok4.setFont(new java.awt.Font("Urbanist Black", 1, 18)); // NOI18N
        labelNama2_Kelompok4.setForeground(new java.awt.Color(255, 255, 255));
        labelNama2_Kelompok4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelNama2_Kelompok4.setText("Irenius Bonan");
        panelNama2_Kelompok03.add(labelNama2_Kelompok4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 170, 30));

        panelTentang_Kelompok03.add(panelNama2_Kelompok03, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 510, 190, 30));

        panelNama3_Kelompok03.setBackground(new java.awt.Color(21, 0, 53));
        panelNama3_Kelompok03.setRoundBottomLeft(15);
        panelNama3_Kelompok03.setRoundBottomRight(15);
        panelNama3_Kelompok03.setRoundTopLeft(15);
        panelNama3_Kelompok03.setRoundTopRight(15);
        panelNama3_Kelompok03.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                panelNama3_Kelompok03MouseMoved(evt);
            }
        });
        panelNama3_Kelompok03.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelNama2_Kelompok5.setFont(new java.awt.Font("Urbanist Black", 1, 18)); // NOI18N
        labelNama2_Kelompok5.setForeground(new java.awt.Color(255, 255, 255));
        labelNama2_Kelompok5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelNama2_Kelompok5.setText("Irma Fitriani ");
        panelNama3_Kelompok03.add(labelNama2_Kelompok5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 170, 30));

        panelTentang_Kelompok03.add(panelNama3_Kelompok03, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 510, 190, 30));

        panelNama4_Kelompok03.setBackground(new java.awt.Color(21, 0, 53));
        panelNama4_Kelompok03.setRoundBottomLeft(15);
        panelNama4_Kelompok03.setRoundBottomRight(15);
        panelNama4_Kelompok03.setRoundTopLeft(15);
        panelNama4_Kelompok03.setRoundTopRight(15);
        panelNama4_Kelompok03.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                panelNama4_Kelompok03MouseMoved(evt);
            }
        });
        panelNama4_Kelompok03.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelNama2_Kelompok6.setFont(new java.awt.Font("Urbanist Black", 1, 18)); // NOI18N
        labelNama2_Kelompok6.setForeground(new java.awt.Color(255, 255, 255));
        labelNama2_Kelompok6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelNama2_Kelompok6.setText("Dian Sri H ");
        panelNama4_Kelompok03.add(labelNama2_Kelompok6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 170, 30));

        panelTentang_Kelompok03.add(panelNama4_Kelompok03, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 510, 190, 30));

        panelNama5_Kelompok03.setBackground(new java.awt.Color(21, 0, 53));
        panelNama5_Kelompok03.setRoundBottomLeft(15);
        panelNama5_Kelompok03.setRoundBottomRight(15);
        panelNama5_Kelompok03.setRoundTopLeft(15);
        panelNama5_Kelompok03.setRoundTopRight(15);
        panelNama5_Kelompok03.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                panelNama5_Kelompok03MouseMoved(evt);
            }
        });
        panelNama5_Kelompok03.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelNama2_Kelompok7.setFont(new java.awt.Font("Urbanist Black", 1, 18)); // NOI18N
        labelNama2_Kelompok7.setForeground(new java.awt.Color(255, 255, 255));
        labelNama2_Kelompok7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelNama2_Kelompok7.setText("Barhan Najib ");
        panelNama5_Kelompok03.add(labelNama2_Kelompok7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 170, 30));

        panelTentang_Kelompok03.add(panelNama5_Kelompok03, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 510, 190, 30));

        panelKembali_Kelompok03.setBackground(new java.awt.Color(21, 0, 53));
        panelKembali_Kelompok03.setRoundBottomLeft(35);
        panelKembali_Kelompok03.setRoundBottomRight(35);
        panelKembali_Kelompok03.setRoundTopLeft(35);
        panelKembali_Kelompok03.setRoundTopRight(35);
        panelKembali_Kelompok03.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                panelKembali_Kelompok03MouseMoved(evt);
            }
        });
        panelKembali_Kelompok03.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelKembali_Kelompok03.setFont(new java.awt.Font("Urbanist", 1, 18)); // NOI18N
        labelKembali_Kelompok03.setForeground(new java.awt.Color(255, 255, 255));
        labelKembali_Kelompok03.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelKembali_Kelompok03.setText("Kembali");
        labelKembali_Kelompok03.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelKembali_Kelompok03.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                labelKembali_Kelompok03MouseMoved(evt);
            }
        });
        labelKembali_Kelompok03.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelKembali_Kelompok03MouseClicked(evt);
            }
        });
        panelKembali_Kelompok03.add(labelKembali_Kelompok03, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 5, 120, 30));

        panelTentang_Kelompok03.add(panelKembali_Kelompok03, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 630, 140, 40));

        labelGambar1_Kelompok03.setFont(new java.awt.Font("Urbanist", 1, 18)); // NOI18N
        labelGambar1_Kelompok03.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelGambar1_Kelompok03.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Form Pilihan APK.png"))); // NOI18N
        labelGambar1_Kelompok03.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                labelGambar1_Kelompok03MouseMoved(evt);
            }
        });
        panelTentang_Kelompok03.add(labelGambar1_Kelompok03, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        labelGambar2_Kelompok03.setFont(new java.awt.Font("Urbanist", 1, 18)); // NOI18N
        labelGambar2_Kelompok03.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelGambar2_Kelompok03.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Form Tentang.png"))); // NOI18N
        labelGambar2_Kelompok03.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                labelGambar2_Kelompok03MouseMoved(evt);
            }
        });
        panelTentang_Kelompok03.add(labelGambar2_Kelompok03, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        labelKet_Kelompok5.setFont(new java.awt.Font("Urbanist Black", 1, 30)); // NOI18N
        labelKet_Kelompok5.setForeground(new java.awt.Color(21, 0, 53));
        labelKet_Kelompok5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelKet_Kelompok5.setText("Anggota Yang Terlibat Dalam Pengembangan Aplikasi");
        panelTentang_Kelompok03.add(labelKet_Kelompok5, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 110, 1260, -1));

        getContentPane().add(panelTentang_Kelompok03, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        setSize(new java.awt.Dimension(1296, 759));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void labelGambar_Kelompok03MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelGambar_Kelompok03MouseMoved
        // TODO add your handling code here:
        panelAdmin_Kelompok03.setBackground(new java.awt.Color(21, 0, 53));
        panelPelanggan_Kelompok03.setBackground(new java.awt.Color(21, 0, 53));
        labelAdmin_Kelompok03.setForeground(new java.awt.Color(255, 255, 255));
        labelPelanggan_Kelompok03.setForeground(new java.awt.Color(255, 255, 255));
        labelTentang_Kelompok03.setForeground(new java.awt.Color(21, 0, 53));
        labelTentang_Kelompok03.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Icon Help Kuning.png")));
    }//GEN-LAST:event_labelGambar_Kelompok03MouseMoved

    private void panelAdmin_Kelompok03MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelAdmin_Kelompok03MouseMoved
        // TODO add your handling code here:
        panelAdmin_Kelompok03.setBackground(new java.awt.Color(255, 176, 0));
        labelAdmin_Kelompok03.setForeground(new java.awt.Color(21, 0, 53));
    }//GEN-LAST:event_panelAdmin_Kelompok03MouseMoved

    private void labelAdmin_Kelompok03MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelAdmin_Kelompok03MouseMoved
        // TODO add your handling code here:
        labelAdmin_Kelompok03.setForeground(new java.awt.Color(21, 0, 53));
        panelAdmin_Kelompok03.setBackground(new java.awt.Color(255, 176, 0));
    }//GEN-LAST:event_labelAdmin_Kelompok03MouseMoved

    private void labelAdmin_Kelompok03MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelAdmin_Kelompok03MouseClicked
        // TODO add your handling code here:
        FormLoginAdmin s = new FormLoginAdmin();
        s.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_labelAdmin_Kelompok03MouseClicked

    private void labelPelanggan_Kelompok03MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelPelanggan_Kelompok03MouseMoved
        // TODO add your handling code here:
        
    }//GEN-LAST:event_labelPelanggan_Kelompok03MouseMoved

    private void labelPelanggan_Kelompok03MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelPelanggan_Kelompok03MouseClicked
        // TODO add your handling code here:
        FormLogin s = new FormLogin();
        s.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_labelPelanggan_Kelompok03MouseClicked

    private void panelPelanggan_Kelompok03MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelPelanggan_Kelompok03MouseMoved
        // TODO add your handling code here:
        panelPelanggan_Kelompok03.setBackground(new java.awt.Color(255, 176, 0));
        labelPelanggan_Kelompok03.setForeground(new java.awt.Color(21, 0, 53));
    }//GEN-LAST:event_panelPelanggan_Kelompok03MouseMoved

    private void labelTentang_Kelompok03MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelTentang_Kelompok03MouseMoved
        // TODO add your handling code here:
        labelTentang_Kelompok03.setForeground(new java.awt.Color(255, 255, 255));
        labelTentang_Kelompok03.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Icon Help Hitam.png")));
    }//GEN-LAST:event_labelTentang_Kelompok03MouseMoved

    private void labelGambar1_Kelompok03MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelGambar1_Kelompok03MouseMoved
        // TODO add your handling code here:
        panelKembali_Kelompok03.setBackground(new java.awt.Color(21, 0, 53));
        labelKembali_Kelompok03.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_labelGambar1_Kelompok03MouseMoved

    private void labelTentang_Kelompok03MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelTentang_Kelompok03MouseClicked
        // TODO add your handling code here:
        panel_Kelompok03.setSize(0, 0);
    }//GEN-LAST:event_labelTentang_Kelompok03MouseClicked

    private void labelGambar2_Kelompok03MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelGambar2_Kelompok03MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_labelGambar2_Kelompok03MouseMoved

    private void panelKembali_Kelompok03MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelKembali_Kelompok03MouseMoved
        // TODO add your handling code here:
        panelKembali_Kelompok03.setBackground(new java.awt.Color(255, 176, 0));
        labelKembali_Kelompok03.setForeground(new java.awt.Color(21, 0, 53));
    }//GEN-LAST:event_panelKembali_Kelompok03MouseMoved

    private void labelKembali_Kelompok03MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelKembali_Kelompok03MouseClicked
        // TODO add your handling code here:
        panel_Kelompok03.setSize(1280, 720);
    }//GEN-LAST:event_labelKembali_Kelompok03MouseClicked

    private void labelKembali_Kelompok03MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelKembali_Kelompok03MouseMoved
        // TODO add your handling code here:
        labelKembali_Kelompok03.setForeground(new java.awt.Color(21, 0, 53));
    }//GEN-LAST:event_labelKembali_Kelompok03MouseMoved

    private void panelNama1_Kelompok03MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelNama1_Kelompok03MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_panelNama1_Kelompok03MouseMoved

    private void panelNama2_Kelompok03MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelNama2_Kelompok03MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_panelNama2_Kelompok03MouseMoved

    private void panelNama3_Kelompok03MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelNama3_Kelompok03MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_panelNama3_Kelompok03MouseMoved

    private void panelNama4_Kelompok03MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelNama4_Kelompok03MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_panelNama4_Kelompok03MouseMoved

    private void panelNama5_Kelompok03MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelNama5_Kelompok03MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_panelNama5_Kelompok03MouseMoved

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPilihanAplikasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPilihanAplikasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPilihanAplikasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPilihanAplikasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormPilihanAplikasi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel GmbrPlg_Kelompok03;
    private javax.swing.JLabel labelAdmin_Kelompok03;
    private javax.swing.JLabel labelCartin_Kelompok03;
    private javax.swing.JLabel labelCartin_Kelompok4;
    private javax.swing.JLabel labelFood_Kelompok03;
    private javax.swing.JLabel labelFood_Kelompok4;
    private javax.swing.JLabel labelGambar1_Kelompok03;
    private javax.swing.JLabel labelGambar2_Kelompok03;
    private javax.swing.JLabel labelGambar_Kelompok03;
    private javax.swing.JLabel labelGmbrAdmin_Kelompok03;
    private javax.swing.JLabel labelKembali_Kelompok03;
    private javax.swing.JLabel labelKet_Kelompok03;
    private javax.swing.JLabel labelKet_Kelompok5;
    private javax.swing.JLabel labelNama2_Kelompok03;
    private javax.swing.JLabel labelNama2_Kelompok4;
    private javax.swing.JLabel labelNama2_Kelompok5;
    private javax.swing.JLabel labelNama2_Kelompok6;
    private javax.swing.JLabel labelNama2_Kelompok7;
    private javax.swing.JLabel labelPelanggan_Kelompok03;
    private javax.swing.JLabel labelTentang_Kelompok03;
    private ClassForGUI.PanelRound panelAdmin_Kelompok03;
    private ClassForGUI.PanelRound panelGmbrAdmin_Kelompok03;
    private ClassForGUI.PanelRound panelGmbrPlg_Kelompok03;
    private ClassForGUI.PanelRound panelKembali_Kelompok03;
    private ClassForGUI.PanelRound panelNama1_Kelompok03;
    private ClassForGUI.PanelRound panelNama2_Kelompok03;
    private ClassForGUI.PanelRound panelNama3_Kelompok03;
    private ClassForGUI.PanelRound panelNama4_Kelompok03;
    private ClassForGUI.PanelRound panelNama5_Kelompok03;
    private ClassForGUI.PanelRound panelPelanggan_Kelompok03;
    private javax.swing.JPanel panelTentang_Kelompok03;
    private javax.swing.JPanel panel_Kelompok03;
    // End of variables declaration//GEN-END:variables
}
